import {chromium,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const nav=async name=>{if(await page.getByRole('button',{name:'Toggle navigation'}).isVisible()&&!await page.locator('.sidebar').evaluate(e=>e.classList.contains('open')))await page.getByRole('button',{name:'Toggle navigation'}).click();await page.locator('nav').getByRole('button',{name,exact:true}).click()};
try{
 await page.goto('http://127.0.0.1:5188');
 await nav('Roadmap');
 await expect(page.locator('.curriculum-row')).toHaveCount(30);
 await page.getByLabel('Search curriculum',{exact:true}).fill('decorator');
 await expect(page.locator('.curriculum-row').filter({hasText:'Applying a decorator'})).toContainText('WEEK 02');
 await page.getByRole('button',{name:'Applying a decorator',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Applying a decorator',exact:true})).toBeVisible();
 for(const title of ['Short explanation','Why this matters','Prerequisites','Code concepts involved','Simple exercise 1','Simple exercise 2','Practical exercise','Debugging exercise','Interview-style question','Explain this in your own words','Notes','Completion checklist'])await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
 await page.getByLabel('Milestone notes',{exact:true}).fill('Decorators transform a callable binding.');
 await page.getByRole('textbox',{name:'Python code: Simple exercise 1',exact:true}).focus();await page.keyboard.press('ControlOrMeta+a');await page.keyboard.insertText('decorated = decorate(original)');
 await page.getByLabel('I read the concept',{exact:true}).check();
 await page.getByLabel('Milestone mastery level',{exact:true}).selectOption('5');
 await page.getByRole('button',{name:'Complete lesson',exact:true}).click();
 await expect(page.getByRole('button',{name:'Mark incomplete',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.reload();
 await page.locator('.search-trigger').click();
 await page.getByPlaceholder('Search concepts and pages...').fill('Applying a decorator');
 await expect(page.locator('.global-milestone-result')).toContainText('Week 2');
 await page.locator('.global-milestone-result').click();
 await expect(page.getByLabel('Milestone notes',{exact:true})).toHaveValue('Decorators transform a callable binding.');
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('mastery-v1')).milestoneAnswers.decorators['simple-1'])).toBe('decorated = decorate(original)');
 await expect(page.getByLabel('I read the concept',{exact:true})).toBeChecked();
 await expect(page.getByLabel('Milestone mastery level',{exact:true})).toHaveValue('5');
 await expect(page.getByRole('button',{name:'Mark incomplete',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Functions as objects Week 1 · Not completed',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Functions as objects',exact:true})).toBeVisible();
 await expect(page.getByLabel('Milestone notes',{exact:true})).toHaveValue('');
 await expect(page.getByLabel('I read the concept',{exact:true})).not.toBeChecked();
 await nav('Roadmap');
 await page.getByLabel('Filter curriculum by tag').selectOption('typing');
 await page.getByLabel('Search curriculum',{exact:true}).fill('Protocol');
 await expect(page.locator('.curriculum-row')).toHaveCount(1);
 await expect(page.locator('.curriculum-row')).toContainText('WEEK 03');
 await page.getByLabel('Search curriculum',{exact:true}).fill('not-a-real-milestone');
 await expect(page.getByRole('heading',{name:'No milestones match these filters.'})).toBeVisible();
 await page.getByRole('button',{name:'Reset search',exact:true}).click();
 await page.screenshot({path:'test-results/roadmap-desktop.png'});
 await page.getByRole('button',{name:'Dependency map',exact:true}).click();
 await page.getByLabel('Dependency map focus').selectOption('hybrid');
 await expect(page.locator('.map-inspector')).toContainText('Hybrid retrieval and rank fusion');
 await expect(page.getByRole('button',{name:'Trace Embeddings and semantic representation, week 7',exact:true})).toBeAttached();
 await expect(page.getByRole('button',{name:'Trace PostgreSQL full-text search, week 7',exact:true})).toBeAttached();
 await page.getByLabel('Dependency map scope').selectOption('all');
 await expect(page.locator('.graph-node')).toHaveCount(152);
 await page.getByLabel('Dependency map zoom').selectOption('0.5');
 await page.screenshot({path:'test-results/dependency-map-desktop.png'});
 await page.getByRole('button',{name:'Open milestone',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Hybrid retrieval and rank fusion',exact:true})).toBeVisible();
 for(const [width,height] of [[375,812],[812,375]]){
  await page.setViewportSize({width,height});
  await nav('Roadmap');
  await page.getByRole('button',{name:'Milestones',exact:true}).click();
  await expect(page.locator('.curriculum-row').first()).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByLabel('Search curriculum',{exact:true}).fill('DBOS');
  await page.getByRole('button',{name:'DBOS workflow registration and execution',exact:true}).click();
  await expect(page.getByRole('heading',{name:'DBOS workflow registration and execution',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await nav('Roadmap');
  await page.getByRole('button',{name:'Dependency map',exact:true}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  if(width===375)await page.screenshot({path:'test-results/dependency-map-mobile.png'});
 }
 expect(errors).toEqual([]);
 console.log('Curriculum browser checks passed: search, week context, detail fields, independent saved work, prerequisite navigation, complete map, mobile layouts.');
}catch(error){await page.screenshot({path:'test-results/curriculum-failure.png'});throw error}finally{await browser.close()}
