const check=(id,name,code,feedback)=>({id,name,code,feedback});
const exercise=(id,title,topic,type,difficulty,description,starterCode,solution,tests,hiddenTests=[],extra={})=>({
 id,title,topic,type,difficulty,description,starterCode,solution,tests,hiddenTests,timeLimit:5000,
 allowedPackages:[],expectedConcepts:[topic],learningObjectives:[description],
 hints:['Write down the input/output contract before coding.','Use the relevant Python protocol and check the empty-input boundary.','Compare one small example with the visible assertions, then handle the edge cases.'],
 explanation:'The reference implements the stated contract and keeps ownership and edge cases explicit. Run the tests, then explain each branch in your own words.',
 commonMistakes:['Only handling the example input.','Mutating caller-owned values unintentionally.','Confusing successful execution with a correct result.'],...extra,
});
export const executableExercises=[
exercise('group-users','Group Users by Country','dicts','Implementation','Easy',
 'Implement group_users(users). Return a dictionary of country → users, preserving order. Put users with no country under "Unknown". Do not mutate the input.',
 'def group_users(users):\n    pass\n',
 'def group_users(users):\n    groups = {}\n    for user in users:\n        groups.setdefault(user.get("country", "Unknown"), []).append(user)\n    return groups\n',
 [check('basic','Basic grouping','users = [{"name":"Ana","country":"Serbia"},{"name":"John","country":"USA"},{"name":"Mark","country":"Serbia"}]\nresult = group_users(users)\nassert len(result["Serbia"]) == 2\nassert result["USA"] == [users[1]]','Group all users under the corresponding country.')],
 [check('empty','Empty list','assert group_users([]) == {}','Return an empty dictionary for no users.'),check('single','Single user','u={"name":"A","country":"RS"}\nassert group_users([u]) == {"RS":[u]}','A single user still belongs in a list.'),check('missing','Missing country','u={"name":"A"}\nassert group_users([u]) == {"Unknown":[u]}','Handle users without a country field under Unknown.'),check('ownership','Order and input ownership','from copy import deepcopy\nu=[{"name":"A","country":"RS"},{"name":"B","country":"RS"}]\nbefore=deepcopy(u)\nassert group_users(u)["RS"] == before\nassert u == before','Keep original order and do not modify caller records.')],
 {hints:['A country can map to more than one user.','A dictionary value can be a list; dict.setdefault can initialize it.','Use user.get("country", "Unknown"), then append to that country’s list.'],explanation:'Each country receives its own list. setdefault creates that list only when the key is absent; append preserves input order. get supplies the documented missing-country value without changing the user.'}),
exercise('mutable-default-fix','Repair a Shared Default','mutable-defaults','Debugging','Easy',
 'Repair add_item so calls with an omitted list are independent. An explicitly supplied list must still be updated and returned.',
 'def add_item(item, items=[]):\n    items.append(item)\n    return items\n',
 'def add_item(item, items=None):\n    if items is None:\n        items = []\n    items.append(item)\n    return items\n',
 [check('separate','Independent default lists','assert add_item(1) == [1]\nassert add_item(2) == [2]','Omitted arguments must allocate a new list on each call.')],
 [check('explicit','Explicit list ownership','items=[]\nassert add_item(3,items) is items\nassert items == [3]','Preserve the explicitly supplied list, even when empty.'),check('none','Explicit None','assert add_item("x",None) == ["x"]','Treat an explicit None like an omitted buffer.')],
 {hints:['When is the default expression evaluated?','Use a sentinel to distinguish omitted storage from provided storage.','Check items is None, not if not items, before allocating a list.'],explanation:'None is immutable. The function allocates a fresh list during each invocation that needs one. An explicit list is retained, including an empty list.'}),
exercise('normalize-level','Normalize a Log Level','define','Implementation','Easy',
 'Implement normalize_level(text): strip surrounding whitespace and return uppercase text. Empty strings are valid.',
 'def normalize_level(text):\n    pass\n','def normalize_level(text):\n    return text.strip().upper()\n',
 [check('basic','Normalize text','assert normalize_level(" info ") == "INFO"','Remove surrounding whitespace and normalize case.')],
 [check('empty','Empty input','assert normalize_level("") == ""','Keep an empty input empty.'),check('already','Already normalized','assert normalize_level("ERROR") == "ERROR"','Normalization should be idempotent.')]),
exercise('pure-normalize','Normalize Without Mutation','mutability','Refactoring','Medium',
 'Refactor normalize(events) to return new dictionaries with uppercase levels while preserving other fields and leaving the caller’s list and records unchanged.',
 'def normalize(events):\n    for event in events:\n        event["level"] = event["level"].upper()\n    return events\n',
 'def normalize(events):\n    return [{**event, "level": event["level"].upper()} for event in events]\n',
 [check('case','Normalize levels','assert normalize([{"level":"info"}]) == [{"level":"INFO"}]','Return normalized records.')],
 [check('mutation','Caller unchanged','events=[{"level":"info","id":1}]\nresult=normalize(events)\nassert events == [{"level":"info","id":1}]\nassert result[0] is not events[0]','Create new records rather than changing the caller’s objects.'),check('empty','Empty stream','assert normalize([]) == []','An empty input needs an empty result.')]),
exercise('decorator-real','Implement a Forwarding Decorator','decorators','Implementation','Medium',
 'Implement doubled(fn), a decorator that doubles the return value, forwards all arguments, and preserves the wrapped name and docstring.',
 'from functools import wraps\n\ndef doubled(fn):\n    pass\n',
 'from functools import wraps\n\ndef doubled(fn):\n    @wraps(fn)\n    def wrapper(*args, **kwargs):\n        return fn(*args, **kwargs) * 2\n    return wrapper\n',
 [check('return','Double the result','@doubled\ndef add(a,b): return a+b\nassert add(2,3) == 10','Return a callable that doubles the function’s result.')],
 [check('forward','Keyword-only forwarding','@doubled\ndef add(a,*,b): return a+b\nassert add(2,b=4) == 12','Forward both positional and keyword arguments.'),check('metadata','Metadata preserved','def original():\n    "Original docs"\n    return 1\nf=doubled(original)\nassert f.__name__ == "original"\nassert f.__doc__ == "Original docs"','Use functools.wraps to preserve metadata.')]),
exercise('decorator-factory-real','Build a Parameterized Decorator','decorator-factories','Implementation','Hard',
 'Implement multiplied(factor). It returns a decorator that multiplies a function’s result by factor, forwards arguments, and preserves metadata.',
 'def multiplied(factor):\n    pass\n',
 'from functools import wraps\n\ndef multiplied(factor):\n    def decorate(fn):\n        @wraps(fn)\n        def wrapper(*args, **kwargs):\n            return fn(*args, **kwargs) * factor\n        return wrapper\n    return decorate\n',
 [check('factor','Configured multiplier','@multiplied(3)\ndef value(x): return x\nassert value(4) == 12','Use the factory’s configured factor.')],
 [check('independent','Independent configurations','def value(x): return x\na,b=multiplied(2)(value),multiplied(5)(value)\nassert a(3)==6 and b(3)==15\nassert a.__name__=="value"','Keep each factory’s configuration independent and preserve metadata.')]),
exercise('generator-real','Stream Positive Values','generators','Implementation','Medium',
 'Implement positives(values) as a lazy generator that yields only values greater than zero. Do not materialize the source.',
 'def positives(values):\n    pass\n','def positives(values):\n    for value in values:\n        if value > 0:\n            yield value\n',
 [check('filter','Filter positives','assert list(positives([-1,0,2,3])) == [2,3]','Yield only positive values.')],
 [check('lazy','Lazy consumption','from itertools import count,islice\nassert list(islice(positives(count()),3)) == [1,2,3]','Process input lazily so an unbounded source can be consumed partially.'),check('generator','Generator protocol','import inspect\nassert inspect.isgenerator(positives([]))','Return a generator, not an eagerly built list.')]),
exercise('context-manager-real','Restore Configuration Reliably','contextlib','Implementation','Hard',
 'Implement temporary_value(config, key, value) as a context manager. Restore the previous value on success or failure; remove keys that were originally absent.',
 'from contextlib import contextmanager\n\n@contextmanager\ndef temporary_value(config, key, value):\n    yield\n',
 'from contextlib import contextmanager\n\n@contextmanager\ndef temporary_value(config, key, value):\n    missing = object()\n    old = config.get(key, missing)\n    config[key] = value\n    try:\n        yield config\n    finally:\n        if old is missing:\n            config.pop(key, None)\n        else:\n            config[key] = old\n',
 [check('restore','Restore existing value','c={"x":1}\nwith temporary_value(c,"x",2): assert c["x"]==2\nassert c["x"]==1','Restore the original value after the block.')],
 [check('failure','Exception cleanup','c={}\ntry:\n    with temporary_value(c,"x",2): raise ValueError("expected")\nexcept ValueError: pass\nelse: raise AssertionError("suppressed exception")\nassert c=={}','Restore missing keys even after exceptions, without suppressing the error.')]),
exercise('async-tasks-real','Collect Concurrent Results','tasks','Async','Medium',
 'Implement async collect(workers): workers is a list of zero-argument async functions. Start all workers concurrently and return their results in input order. Use await directly in this browser runtime.',
 'import asyncio\n\nasync def collect(workers):\n    pass\n',
 'import asyncio\n\nasync def collect(workers):\n    return await asyncio.gather(*(worker() for worker in workers))\n',
 [check('results','Results in input order','async def a():\n    await asyncio.sleep(.01)\n    return "a"\nasync def b(): return "b"\nassert await collect([a,b]) == ["a","b"]','Collect results in input order.')],
 [check('concurrent','Workers overlap','started=0\nready=asyncio.Event()\nasync def worker():\n    global started\n    started+=1\n    if started==3: ready.set()\n    await asyncio.wait_for(ready.wait(),.2)\n    return 1\nassert await collect([worker]*3)==[1,1,1]','Start workers together; sequential awaits cannot satisfy the shared barrier.'),check('empty','No workers','assert await collect([])==[]','An empty worker list returns an empty list.')]),
exercise('typing-boundary','Validate a Typed Boundary','type-narrowing','Typing','Medium',
 'Implement parse_count(value: object) -> int. Accept only nonnegative integers; reject booleans and other types with ValueError. Annotations alone do not enforce this.',
 'def parse_count(value: object) -> int:\n    pass\n',
 'def parse_count(value: object) -> int:\n    if type(value) is not int or value < 0:\n        raise ValueError("nonnegative integer required")\n    return value\n',
 [check('valid','Valid integers','assert parse_count(0)==0 and parse_count(3)==3','Accept zero and positive integers.')],
 [check('invalid','Invalid runtime values','for value in (True,False,-1,"2",None):\n    try: parse_count(value)\n    except ValueError: pass\n    else: raise AssertionError("invalid value accepted")','Reject bool as well as negative and non-integer values.')],
 {explanation:'type(value) is int deliberately excludes bool, which is an int subclass. This runtime experiment complements a static checker; the browser does not run mypy or pyright.'}),
exercise('write-test-real','Test a Normalization Contract','pytest','Testing','Medium',
 'Implement check_normalizer(fn). Return True only if fn strips whitespace, uppercases, and handles an empty input; return False for incorrect or raising implementations. Do not inspect source code.',
 'def check_normalizer(fn):\n    pass\n',
 'def check_normalizer(fn):\n    try:\n        return all(fn(raw) == expected for raw, expected in [(" info ", "INFO"), ("Error", "ERROR"), ("", "")])\n    except Exception:\n        return False\n',
 [check('good','Accept correct behavior','assert check_normalizer(lambda x:x.strip().upper()) is True','Accept a correct implementation.')],
 [check('mutants','Reject broken variants','assert check_normalizer(lambda x:x.upper()) is False\nassert check_normalizer(lambda x:x.strip()) is False\nassert check_normalizer(lambda x:"INFO") is False','Detect missing trimming, casing, and empty-input behavior.'),check('raises','Handle raised errors','def broken(x): raise ValueError("bad")\nassert check_normalizer(broken) is False','A failing implementation should fail the contract check.')]),
exercise('tool-policy-real','Authorize a Tool Call','tool-permissions','AI Engineering','Hard',
 'Implement authorize(auth, customer, operation). Return True only when tenant IDs match and operation is in auth["scopes"]. Otherwise raise PermissionError. Missing identity must be denied.',
 'def authorize(auth, customer, operation):\n    pass\n',
 'def authorize(auth, customer, operation):\n    if not auth.get("tenant") or auth["tenant"] != customer.get("tenant") or operation not in auth.get("scopes", []):\n        raise PermissionError("denied")\n    return True\n',
 [check('allowed','Authorized access','assert authorize({"tenant":"a","scopes":["read"]},{"tenant":"a"},"read") is True','Allow an explicitly scoped operation for the same tenant.')],
 [check('denied','Cross-tenant and missing scope','for auth,customer,op in [({"tenant":"a","scopes":["read"]},{"tenant":"b"},"read"),({"tenant":"a","scopes":["read"]},{"tenant":"a"},"write"),({},{},"read")]:\n    try: authorize(auth,customer,op)\n    except PermissionError: pass\n    else: raise AssertionError("unauthorized")','Deny cross-tenant, unscoped, and missing-identity calls.')]),
exercise('architecture-retry','Design Idempotent Submission','idempotency','Architecture','Advanced',
 'First describe your data flow and failure boundaries. Then implement submit(store, key, payload): reuse the stored result on an identical retry, raise ValueError on a changed payload. This sequential fake does not provide distributed atomicity.',
 'def submit(store, key, payload):\n    pass\n',
 'from copy import deepcopy\n\ndef submit(store, key, payload):\n    if key in store and store[key] != payload:\n        raise ValueError("idempotency conflict")\n    if key not in store:\n        store[key] = deepcopy(payload)\n    return deepcopy(store[key])\n',
 [check('retry','Identical retries','s={}\nassert submit(s,"r1",{"note":"a"}) == submit(s,"r1",{"note":"a"})\nassert len(s)==1','Reuse the original effect for repeated request identity.')],
 [check('conflict','Changed payload','s={}\nsubmit(s,"r1",{"note":"a"})\ntry: submit(s,"r1",{"note":"b"})\nexcept ValueError: pass\nelse: raise AssertionError("conflict accepted")','Reject reuse of a key with a changed payload.'),check('isolate','Snapshot ownership','s={}; p={"note":["a"]}\nr=submit(s,"r1",p); p["note"].append("b"); r["note"].append("c")\nassert s["r1"]=={"note":["a"]}','Store and return isolated payload snapshots.')]),
exercise('pydantic-note-real','Validate a Support Note','base-model','AI Engineering','Medium',
 'Define Note(BaseModel) with customer_id: int strictly greater than zero and text: str between 1 and 500 characters. Pydantic loads only when you run this exercise.',
 'from pydantic import BaseModel, Field\n\nclass Note(BaseModel):\n    pass\n',
 'from pydantic import BaseModel, Field\n\nclass Note(BaseModel):\n    customer_id: int = Field(gt=0)\n    text: str = Field(min_length=1, max_length=500)\n',
 [check('valid','Valid payload','assert Note(customer_id=1,text="hello").text == "hello"','Accept valid note data.')],
 [check('invalid','Reject invalid boundaries','from pydantic import ValidationError\nfor payload in ({"customer_id":0,"text":"a"},{"customer_id":1,"text":""},{"customer_id":1,"text":"a"*501}):\n    try: Note.model_validate(payload)\n    except ValidationError: pass\n    else: raise AssertionError("invalid input accepted")','Enforce positive IDs and the text-length limits.')],{allowedPackages:['pydantic']}),
];
const predictions=[
 ['references','bindings','References','a = [1, 2]\nb = a\nb.append(3)\nprint(a)','[1, 2, 3]'],
 ['identity','identity','Identity','a = [1]\nb = [1]\nprint(a == b, a is b)','True False'],
 ['scope','scope','Scope','x = "global"\ndef f():\n    x = "local"\n    return x\nprint(f(), x)','local global'],
 ['closures','closures','Closures','functions = [lambda: i for i in range(3)]\nprint([f() for f in functions])','[2, 2, 2]'],
 ['generators','generators','Generator Exhaustion','values = (n * 2 for n in range(3))\nprint(list(values))\nprint(list(values))','[0, 2, 4]\n[]'],
 ['class-state','attributes','Class Attributes','class Customer:\n    notes = []\na, b = Customer(), Customer()\na.notes.append("hello")\nprint(b.notes)','[\'hello\']'],
 ['defaults','mutable-defaults','Default Arguments','def add(x, values=[]):\n    values.append(x)\n    return values\nprint(add(1))\nprint(add(2))','[1]\n[1, 2]'],
 ['mutation','mutability','Nested Mutability','outer = ([1],)\nouter[0].append(2)\nprint(outer)','([1, 2],)'],
 ['async','await','Await Behavior','import asyncio\nasync def immediate():\n    return 1\nasync def main():\n    print("before")\n    await immediate()\n    print("after")\nawait main()','before\nafter'],
];
for(const [id,topic,title,code,expectedOutput] of predictions){
 executableExercises.push(exercise('predict-'+id,'Predict '+title,topic,'Prediction','Easy','Read the fixed program and submit its exact output before running. Explain why the values and control flow produce it.',code,code,[],[],{expectedOutput,completionRule:'prediction',explanation:`Expected output:\n${expectedOutput}\nTrace each binding and suspension point; code runs only after you commit your prediction.`,hints:['Trace the program one statement at a time.','Distinguish a reference from a copy, and creation from execution.','Record each print separately, including brackets and quotation marks.']}));
}
executableExercises.push(exercise('read-dispatch','Read a Function Registry','function-objects','Code Reading','Easy',
 'Read the registry, then implement explain_dispatch() returning the value of registry["upper"]("info"). The registry stores functions, not their results.',
 'registry = {"upper": str.upper, "lower": str.lower}\n\ndef explain_dispatch():\n    pass\n',
 'registry = {"upper": str.upper, "lower": str.lower}\n\ndef explain_dispatch():\n    return registry["upper"]("info")\n',
 [check('value','Callable lookup','assert explain_dispatch()=="INFO"','Look up the callable, then invoke it on the text.')],[]));
export const executableById=Object.fromEntries(executableExercises.map(e=>[e.id,e]));
export const exerciseTypes=['Implementation','Debugging','Code Reading','Refactoring','Prediction','Architecture','Async','Testing','Typing','AI Engineering'];
export function executableFor(topic,kind){
 const aliases={lists:'dicts',dicts:'dicts',returns:'define',keywords:'define','function-objects':'function-objects','decorator-forwarding':'decorators','context-managers':'contextlib',iterators:'generators',gather:'tasks',coroutines:'tasks','coroutine-call':'tasks',annotations:'type-narrowing',protocol:'type-narrowing','pydantic-fields':'base-model','agent-tools':'tool-permissions'};
 const id=aliases[topic]||topic;
 const matches=executableExercises.filter(e=>e.topic===id);
 if(kind==='debugging')return matches.find(e=>e.type==='Debugging'||e.type==='Refactoring');
 if(kind==='prediction')return matches.find(e=>e.type==='Prediction');
 return matches.find(e=>e.type!=='Prediction');
}
export const playgroundExamples={
 Lists:'values = [1, 2, 3]\nprint([n*n for n in values])\n',
 Dictionaries:'counts = {}\nfor word in ["python", "ai", "python"]:\n    counts[word] = counts.get(word, 0) + 1\nprint(counts)\n',
 Functions:'def greet(name, *, prefix="Hello"):\n    return f"{prefix}, {name}"\n\nprint(greet("engineer"))\n',
 Classes:'class Counter:\n    def __init__(self): self.value = 0\n    def increment(self): self.value += 1\n\nc = Counter()\nc.increment()\nprint(c.value)\n',
 Decorators:'def traced(fn):\n    def wrapper(*args, **kwargs):\n        print("calling", fn.__name__)\n        return fn(*args, **kwargs)\n    return wrapper\n\n@traced\ndef double(n): return n * 2\n\nprint(double(3))\n',
 Generators:'def squares(n):\n    for value in range(n):\n        yield value * value\n\nstream = squares(3)\nprint(next(stream))\nprint(list(stream))\n',
 'Context Managers':'from contextlib import contextmanager\n\n@contextmanager\ndef scope():\n    print("enter")\n    try: yield\n    finally: print("exit")\n\nwith scope(): print("inside")\n',
 Asyncio:'import asyncio\n\nasync def work(n):\n    await asyncio.sleep(.01)\n    return n * 2\n\nprint(await asyncio.gather(work(1), work(2)))\n',
 Dataclasses:'from dataclasses import dataclass, field\n\n@dataclass\nclass Event:\n    name: str\n    tags: list[str] = field(default_factory=list)\n\nprint(Event("ready"))\n',
 Typing:'def double(value: int) -> int:\n    return value * 2\n\nprint(double(3))\nprint(double("a"))  # Annotations do not enforce runtime types.\n',
};
