const rows=String.raw`shallow-copy|original = [["open"]]\ncopy = original.copy()\ncopy.append(["new"] )\ncopy[0].append("closed")\nprint(original)\nprint(len(copy))|[['open', 'closed']]\n2|copy creates a new outer list, so appending a new row does not lengthen original. Both outer lists still point to the same first inner list, whose mutation is visible through either route.|A shallow copy separates only the outer container.|Print original[0] is copy[0], then copy is original.
deep-copy|from copy import deepcopy\noriginal = {"flags": ["safe"]}\ncopy = deepcopy(original)\ncopy["flags"].append("fast")\nprint(original["flags"])\nprint(copy["flags"])|['safe']\n['safe', 'fast']|deepcopy recursively creates an independent nested list here. The change reaches only the new graph. Real resources such as sockets need explicit ownership rather than blind recursive copying.|Deep copying an entire application object graph is not a resource-management strategy.|Repeat with dict.copy and explain the changed result.
classes|class Counter:\n    def __init__(self, start):\n        self.value = start\n    def increment(self):\n        self.value += 1\ncounter = Counter(4)\ncounter.increment()\nprint(counter.value)|5|Calling Counter creates an instance and initializes its value. Accessing increment through that instance binds self, so the method changes that particular object's state.|self is supplied by a bound method call, not a magic global variable.|Create a second counter and show that incrementing the first leaves it unchanged.
attributes|class Notebook:\n    category = "notes"\n    def __init__(self):\n        self.pages = []\na, b = Notebook(), Notebook()\na.pages.append("idea")\nprint(a.category, b.category)\nprint(a.pages, b.pages)|notes notes\n['idea'] []|category is shared on the class. __init__ allocates a pages list for each instance, so mutable state is separate. Attribute lookup can find a class value when the instance has no override.|A mutable class attribute is shared by every instance using it.|Move pages to the class body and predict the new output.
composition|class Console:\n    def send(self, text):\n        print(text)\nclass Reporter:\n    def __init__(self, output):\n        self.output = output\n    def report(self):\n        self.output.send("ready")\nReporter(Console()).report()|ready|Reporter owns a reference to a collaborator and delegates sending. It does not inherit Console's identity or implementation. Replacing the collaborator changes delivery without changing report orchestration.|Inheritance is not required merely to reuse another object's behavior.|Inject an object that records messages in a list instead of printing.
dataclasses|from dataclasses import dataclass, field\n@dataclass\nclass Batch:\n    name: str\n    items: list = field(default_factory=list)\na, b = Batch("a"), Batch("b")\na.items.append(1)\nprint(a)\nprint(b.items)|Batch(name='a', items=[1])\n[]|dataclass generates initialization and representation from declared fields. default_factory calls list separately for each instance, avoiding a shared collection. Annotations still do not validate element types at runtime.|A dataclass is not a Pydantic validation boundary.|Construct a Batch with an unexpected name type and compare runtime behavior with a static checker.
properties|class Temperature:\n    def __init__(self, celsius):\n        self.celsius = celsius\n    @property\n    def fahrenheit(self):\n        return self.celsius * 9 / 5 + 32\nt = Temperature(20)\nprint(t.fahrenheit)\nt.celsius = 0\nprint(t.fahrenheit)|68.0\n32.0|Accessing fahrenheit invokes its getter through attribute syntax. The value is computed from current state instead of stored separately, avoiding stale duplicated data.|A property without a setter cannot be assigned like a normal stored field.|Try assigning fahrenheit and explain why Python rejects it.
method-kinds|class Label:\n    prefix = "item"\n    @classmethod\n    def named(cls, value):\n        return f"{cls.prefix}:{value}"\n    @staticmethod\n    def clean(value):\n        return value.strip()\nprint(Label.named("7"))\nprint(Label.clean(" x "))|item:7\nx|The class method receives the class as cls and can respect subclass configuration. The static method receives neither an instance nor a class; it is a namespaced helper.|classmethod is not just an instance method that you happen to call on the class.|Subclass Label with a new prefix and call named on the subclass.
dunders|class Playlist:\n    def __init__(self, songs):\n        self.songs = songs\n    def __len__(self):\n        return len(self.songs)\nprint(len(Playlist(["intro", "outro"])))|2|len delegates to the type's length protocol. Implementing __len__ makes the object participate in ordinary syntax without exposing its internal list to callers.|Special methods must honor the protocol's expected result and error behavior.|Return a negative length and observe Python's validation of the protocol.
iterables|values = [3, 4]\nfirst = iter(values)\nsecond = iter(values)\nprint(next(first), next(first))\nprint(next(second))|3 4\n3|A list can produce independent iterators. Each iterator owns its position, so advancing first does not advance second. An iterable is the source of iteration, not necessarily the cursor itself.|An iterable and an iterator are different roles even when one object implements both.|Compare iter(first) is first with iter(values) is values.
iterators|cursor = iter([9])\nprint(next(cursor))\nprint(next(cursor, "done"))\nprint(next(cursor, "done"))|9\ndone\ndone|The iterator yields its single element and then stays exhausted. The two-argument next supplies a fallback instead of exposing StopIteration. No rewind occurs automatically.|Calling iter on an exhausted iterator does not reset it.|Remove the fallback and catch StopIteration explicitly.
generators|def sequence():\n    print("start")\n    yield 8\n    print("resume")\n    yield 9\nstream = sequence()\nprint("created")\nprint(next(stream))\nprint(next(stream))|created\nstart\n8\nresume\n9|Creating the generator does not execute its body. Each next advances to a yield and returns that yielded value; locals and the instruction position survive between calls.|yield pauses a function; return finishes it.|Request one more value and explain the resulting StopIteration.
generator-pipelines|source = (n for n in range(6))\nfiltered = (n for n in source if n % 2 == 0)\nsquared = (n * n for n in filtered)\nprint(next(squared))\nprint(list(squared))\nprint(list(source))|0\n[4, 16]\n[]|Requesting an output pulls only enough input through the pipeline to produce it. Consuming the rest drains the shared source, including values rejected by the filter.|Laziness avoids eager storage but does not make a stream reusable.|Replace the source generator with a list and create two independent pipelines.
generator-cleanup|def stream():\n    try:\n        yield "row"\n        yield "later"\n    finally:\n        print("closed")\ncursor = stream()\nprint(next(cursor))\ncursor.close()|row\nclosed|The first next enters the try block and suspends at yield. Explicit close causes the generator to unwind through finally. Cleanup ownership should be deliberate when consumers may stop early.|Do not assume a loop break immediately closes every referenced generator.|Keep a reference after breaking from a loop, then close it explicitly.
decorators|def loud(function):\n    def wrapper():\n        return function().upper()\n    return wrapper\n@loud\ndef greeting():\n    return "hello"\nprint(greeting())|HELLO|Python creates greeting, passes it to loud and binds the returned wrapper to greeting. The later call enters the wrapper, which calls the original function and transforms its result.|Decoration happens when the definition executes, not on every invocation.|Replace @loud with greeting = loud(greeting) after a plain definition.
decorator-forwarding|from functools import wraps\ndef traced(function):\n    @wraps(function)\n    def wrapper(*args, **kwargs):\n        return function(*args, **kwargs)\n    return wrapper\n@traced\ndef total(a, *, b):\n    return a + b\nprint(total(2, b=6))\nprint(total.__name__)|8\ntotal|The wrapper collects both argument kinds and expands them back into the original call. wraps preserves descriptive metadata; it does not do the forwarding for you.|A wrapper accepting only positional arguments breaks keyword-only calls.|Remove wraps and compare __name__; then remove **kwargs and observe the failed call.
decorator-factories|def suffix(mark):\n    def decorate(function):\n        def wrapper():\n            return function() + mark\n        return wrapper\n    return decorate\n@suffix("!")\ndef greeting():\n    return "hello"\nprint(greeting())|hello!|suffix first saves configuration and returns a decorator. The decorator receives the function and returns a wrapper. Only the wrapper executes when greeting is called.|There are three different calls: configure, decorate and invoke.|Create another decorated function with a question-mark suffix.
decorator-order|def wrap(mark):\n    def decorate(function):\n        return lambda: mark + function() + mark\n    return decorate\n@wrap("A")\n@wrap("B")\ndef value():\n    return "x"\nprint(value())|ABxBA|The inner decorator is applied first, giving wrap(A)(wrap(B)(value)). At invocation, the outer wrapper surrounds the inner result. Changing order can change authentication, caching and logging behavior too.|The top decorator is the outermost wrapper, not the first one applied.|Swap A and B and predict the complete result.
context-managers|class Notice:\n    def __enter__(self):\n        print("enter")\n        return "resource"\n    def __exit__(self, kind, error, traceback):\n        print("exit")\n        return False\nwith Notice() as value:\n    print(value)|enter\nresource\nexit|with calls __enter__ and binds its return value to value. After the body, __exit__ runs. False means any body exception should propagate rather than be suppressed.|The value after as is the result of __enter__, not necessarily the manager object.|Raise ValueError in the body and catch it outside the with statement.
contextlib|from contextlib import contextmanager\n@contextmanager\ndef notice():\n    print("acquire")\n    try:\n        yield "resource"\n    finally:\n        print("release")\nwith notice() as value:\n    print(value)|acquire\nresource\nrelease|The decorator adapts a one-yield generator to the context-manager protocol. Code before yield acquires; the yielded value enters the body; finally releases on normal and exceptional exit.|A contextmanager generator must yield exactly once for each entered context.|Raise an exception inside the with block and check that release still prints.`;
export default rows;
