// Independent teaching examples; these are not the exercise answer bank.
// id | Python | expected output | walkthrough | common trap | experiment
const rows=String.raw`bindings|bag = ["apple"]\nsecond_name = bag\nsecond_name.append("pear")\nprint(bag)\nsecond_name = ["plum"]\nprint(bag)|['apple', 'pear']\n['apple', 'pear']|The first assignment creates one list. Both names then refer to it, so append is visible through bag. Reassigning second_name creates a new binding without touching the original list.|An assignment does not copy a mutable object.|Replace the reassignment with second_name.clear(). Predict what bag contains.
mutability|box = (["draft"],)\nbox[0].append("reviewed")\nprint(box)\nprint(type(box).__name__)|(['draft', 'reviewed'],)\ntuple|The tuple keeps the same reference in its only slot. The list reached through that slot can still change. Immutability describes the tuple's own structure, not everything reachable from it.|Immutable does not mean recursively frozen.|Try replacing box[0] instead of appending to the nested list. Explain the TypeError.
identity|left = [7]\nright = [7]\nalias = left\nprint(left == right)\nprint(left is right)\nprint(left is alias)|True\nFalse\nTrue|The two list displays allocate separate objects with equal contents. alias adds another name for left's object. Equality asks about values; identity asks whether there is just one object.|Do not use is to compare strings or numbers by value.|Change right[0] and predict which other names observe the change.
truth|def timeout(value):\n    return 10 if value is None else value\nprint(timeout(None))\nprint(timeout(0))\nprint(0 or 10)|10\n0\n10|The explicit None check preserves a deliberately supplied zero. The or expression chooses its second operand whenever the first is false, including valid zero values.|Missing and false are different conditions.|Try an empty string and False, then decide which values your API should accept.
numbers|from decimal import Decimal\nprint(0.1 + 0.2 == 0.3)\nprice = Decimal("0.10")\nprint(price * 3)|False\n0.30|Binary floating point cannot exactly represent every decimal fraction. Constructing Decimal from text preserves the decimal quantity before arithmetic begins.|Decimal(0.1) starts with the already-approximated float.|Print Decimal(0.1) and compare it with Decimal("0.1").
strings|word = "caf\u00e9"\nencoded = word.encode("utf-8")\nprint(len(word), len(encoded))\nprint(word[1:3])\nprint(encoded.decode("utf-8") == word)|4 5\naf\nTrue|The string has four Unicode code points, while UTF-8 uses five bytes here. The slice includes indexes 1 and 2, but excludes 3. Decoding reconstructs the text before character-level work.|Byte offsets and string indexes are not interchangeable.|Slice the encoded bytes inside the final character and observe the decoding failure.
lists|first = [1]\nsecond = [1]\nfirst.append([2, 3])\nsecond.extend([2, 3])\nprint(first)\nprint(second)|[1, [2, 3]]\n[1, 2, 3]|append adds its argument as one element. extend iterates over its argument and adds each element. Both methods mutate the existing list.|Assigning the result of append replaces your variable with None.|Store the return value of append and print it next to the list.
dicts|buckets = {}\nfor kind in ["warning", "info", "warning"]:\n    buckets.setdefault(kind, []).append(kind)\nprint(buckets["warning"])\nprint(buckets.get("error", []))|['warning', 'warning']\n[]|setdefault returns the stored list when a key exists and installs a new list otherwise. Appending changes that bucket. get returns a fallback without adding an absent key.|Reusing one mutable list as every bucket joins unrelated groups.|Check whether error is in buckets after the get call.
sets|registered = {"a", "b", "c"}\nactive = {"b", "c", "d"}\nprint(sorted(registered & active))\nprint(sorted(registered - active))|['b', 'c']\n['a']|Intersection selects shared members; subtraction selects members present only on the left. Sorting is used only to make the displayed result deterministic.|Set iteration order is not an ordering contract.|Try adding a list to a set, then represent the same values with a tuple.
unpack|record = (201, "created", "job-8", 4)\nstatus, message, *details = record\nprint(status, message)\nprint(details)|201 created\n['job-8', 4]|The first two names receive individual elements. The starred target collects all remaining elements into a list, even though the source is a tuple.|A starred target is a list, not necessarily the source's container type.|Remove the last two source elements and inspect details.
loops|for number in range(2, 5):\n    print(number)\nelse:\n    print("finished")|2\n3\n4\nfinished|range starts at 2 and stops before 5. The loop else runs because iteration finishes without a break. It is attached to the loop, not to an if inside it.|An exclusive stop is not the last emitted value.|Break when number is 3 and predict whether finished is printed.
comprehensions|readings = [-2, 0, 3, 5]\npositive_squares = [n * n for n in readings if n > 0]\nprint(positive_squares)\nprint(readings)|[9, 25]\n[-2, 0, 3, 5]|The filter decides which input values survive; the expression computes an output for each survivor. A new list is created and the input is untouched.|A comprehension with side effects can hide execution order.|Move the filtering into a normal loop and compare both versions.
exceptions|try:\n    count = int("many")\nexcept ValueError:\n    print("not a number")\nfinally:\n    print("cleanup")|not a number\ncleanup|int raises before count is assigned. The matching handler runs, and finally runs afterward whether parsing succeeded or failed. Narrow handling keeps unrelated failures visible.|Catching every Exception can disguise programming errors as invalid input.|Replace many with 12 and predict which messages remain.
files|from pathlib import Path\nfrom tempfile import TemporaryDirectory\nwith TemporaryDirectory() as folder:\n    path = Path(folder) / "note.txt"\n    path.write_text("ready", encoding="utf-8")\n    with path.open(encoding="utf-8") as handle:\n        print(handle.read())\n    print(handle.closed)|ready\nTrue|Path describes the location; open creates the resource. Exiting the inner with closes the file even if its body fails. The temporary directory isolates this example's filesystem changes.|A path object is not an open file handle.|Raise an exception inside the file block and inspect closed in a handler outside it.
json|import json\npayload = json.loads('{"active": true, "count": 2}')\nprint(payload["active"], type(payload["count"]).__name__)\nprint(isinstance(json.loads("[]"), dict))|True int\nFalse|JSON booleans and numbers become Python values. A JSON array is valid syntax but becomes a list, so a caller expecting an object must still check its contract.|Successful decoding does not prove required fields exist.|Decode null and decide what your boundary should do with the result.
define|def greet(name):\n    """Return a greeting without printing it."""\n    return f"Hello, {name}"\nprint(greet("Mina"))\nprint(callable(greet))|Hello, Mina\nTrue|def binds a callable object. Its body runs only when greet is invoked. The caller chooses to print the returned string, keeping computation separate from display.|Writing greet without parentheses refers to the function; it does not run it.|Assign greet to another variable and call the function through that name.
returns|def show(value):\n    print(value)\ndef double(value):\n    return value * 2\nresult = show(4)\nprint(result)\nprint(double(4) + 1)|4\nNone\n9|show sends text to the console but returns None because it reaches the end. double sends a number to its caller, which can use that result in another expression.|Console output is not a return value.|Add an explicit return to show and compare the stored result.
positional|def subtract(left, right):\n    return left - right\nprint(subtract(9, 2))\nprint(subtract(2, 9))|7\n-7|The first positional argument binds left and the second binds right. Changing order changes meaning even though both inputs have the same type.|Types alone cannot detect every accidentally swapped argument.|Call subtract using keyword arguments in reverse written order.
keywords|def label(name, *, prefix):\n    return f"{prefix}: {name}"\nprint(label("queue", prefix="service"))|service: queue|The bare star makes prefix keyword-only. Naming it at the call site documents its role and prevents it from being accidentally supplied as a second positional value.|A keyword-only parameter still needs a value unless it has a default.|Try label("queue", "service") and explain the error.
defaults|initial = 3\ndef attempts(limit=initial):\n    return limit\ninitial = 8\nprint(attempts())\nprint(attempts(5))|3\n5|The default expression is evaluated while def executes, so changing initial later does not change that saved default. Supplying a value explicitly replaces the default for that call.|Defaults are not recomputed each time a function is called.|Move def below the reassignment and predict the new default.
mutable-defaults|def collect(value, bucket=None):\n    if bucket is None:\n        bucket = []\n    bucket.append(value)\n    return bucket\nprint(collect("red"))\nprint(collect("blue"))|['red']\n['blue']|Each omitted bucket reaches the None branch and gets a fresh list. An explicitly supplied list is deliberately reused. This expresses ownership instead of sharing a hidden default list.|Using bucket or [] incorrectly replaces an explicitly supplied empty list.|Pass the same list into two calls and compare that behavior with omitted arguments.
args|def describe(*values):\n    print(type(values).__name__, len(values))\n    return sum(values)\nprint(describe(2, 5))\nprint(describe())|tuple 2\n7\ntuple 0\n0|The star in the definition collects extra positional arguments into one tuple. With no arguments the tuple is empty; sum has a defined result for that case.|The name args is conventional; the star creates the behavior.|Rename values to numbers and confirm that the behavior is unchanged.
kwargs|def describe(**fields):\n    print(sorted(fields))\n    return fields.get("region", "local")\nprint(describe(service="worker", region="eu"))|['region', 'service']\neu|The double star gathers otherwise-unbound named arguments into a dictionary. Looking up an optional field does not require inventing a positional convention.|Collecting keywords does not validate which keys are allowed.|Reject an unknown key and decide what exception to raise.
argument-unpack|def volume(width, height, depth):\n    return width * height * depth\nsize = (2, 3, 4)\nprint(volume(*size))\nprint(volume(**{"width": 2, "height": 3, "depth": 4}))|24\n24|At a call site, a star expands a sequence into positional arguments; a double star expands a mapping into keyword arguments. The function's signature remains unchanged.|A mapping key that does not match a parameter causes a call error.|Add an extra mapping key and explain why the call is rejected.
annotations|def twice(value: int) -> int:\n    return value * 2\nprint(twice(3))\nprint(twice("ha"))|6\nhaha|Annotations describe the intended contract to readers and tooling. Python still performs string repetition on the second call because no runtime validation was installed.|An annotated function is not automatically a validating boundary.|Run a static checker on the second call and compare its report with runtime behavior.
function-objects|def greet():\n    return "hello"\noperations = {"welcome": greet}\nprint(operations["welcome"]())\nprint(callable(greet), callable(greet()))|hello\nTrue False|The dictionary stores the function object. Looking it up and adding parentheses invokes it. greet() instead produces a string, which cannot be called.|Storing greet() executes immediately and stores its result.|Replace the dictionary value with greet() and predict the failure at dispatch time.
higher-order|def apply_twice(operation, value):\n    return operation(operation(value))\nprint(apply_twice(lambda n: n + 3, 1))|7|The caller supplies behavior as a value. The first application changes 1 to 4; the second changes 4 to 7. The higher-order function does not need to know the operation's implementation.|Passing operation(value) supplies a result instead of a callable.|Pass a doubling function and predict the result before running.
scope|level = "global"\ndef read_local():\n    level = "local"\n    return level\nprint(read_local())\nprint(level)|local\nglobal|Assignment inside read_local creates a local binding. Returning it does not alter the module binding with the same spelling. Each name is resolved in its scope.|Mutating a shared object and rebinding a name are different operations.|Replace the string with a list and mutate it without assigning the name locally.
legb|label = "global"\ndef outer():\n    label = "enclosing"\n    def inner():\n        return label\n    return inner()\nprint(outer())|enclosing|inner has no local label, so ordinary function lookup reaches the enclosing function's binding before the module's. Built-ins are considered after those ordinary scopes.|LEGB is a useful rule for function code, not a complete account of every class or annotation scope.|Add a local label inside inner and predict the result.
closures|def multiplier(factor):\n    def apply(value):\n        return value * factor\n    return apply\ntriple = multiplier(3)\nprint(triple(5))|15|The returned function retains access to the enclosing factor binding after multiplier returns. Each call to multiplier creates a separate enclosing environment.|A closure captures access to bindings, not a frozen copy of every referenced object.|Create a second multiplier with factor 4 and show that the two functions behave independently.`;
export default rows;
