export const weeks = [
  {
    "id": 0,
    "title": "Python Fluency",
    "short": "Python fluency",
    "concepts": [
      "Variables",
      "Python object model introduction",
      "None",
      "Booleans",
      "Numbers",
      "Strings",
      "Lists",
      "Tuples",
      "Sets",
      "Dictionaries",
      "Indexing",
      "Slicing",
      "Loops",
      "range",
      "Conditions",
      "Comprehensions",
      "Unpacking",
      "Functions",
      "Arguments",
      "Keyword arguments",
      "args",
      "kwargs",
      "Scope",
      "Exceptions",
      "File handling",
      "pathlib",
      "JSON",
      "Standard library basics",
      "Mutability",
      "References",
      "Equality versus identity"
    ],
    "project": "Build a framework-free log analyzer",
    "exercises": [
      "Transform, filter, group, and aggregate JSON data.",
      "Read log files with pathlib and summarize error rates."
    ],
    "criteria": "The learner can solve common data manipulation tasks without AI assistance. The learner can explain mutability, references, identity, copying, and function arguments."
  },
  {
    "id": 1,
    "title": "Python Internals and Language Model",
    "short": "Internals",
    "concepts": [
      "Objects",
      "Identity",
      "Equality",
      "Mutable and immutable objects",
      "References",
      "Shallow copy",
      "Deep copy",
      "Classes",
      "Instance attributes",
      "Class attributes",
      "Dataclasses",
      "Inheritance",
      "Composition",
      "Properties",
      "Static methods",
      "Class methods",
      "Magic methods",
      "Dunder methods",
      "Iterable",
      "Iterator",
      "Generator",
      "yield",
      "Decorators",
      "Closures",
      "Context managers",
      "Enums",
      "Descriptors introduction"
    ],
    "project": "Build a dataclass-based domain model",
    "exercises": [
      "Implement a decorator, iterator, generator pipeline, and context manager.",
      "Build classes with composition."
    ],
    "criteria": "The learner understands why Python frameworks use decorators so heavily. The learner can explain how generators, iterators, decorators, context managers, and classes actually work."
  },
  {
    "id": 2,
    "title": "Professional Python Engineering",
    "short": "Engineering",
    "concepts": [
      "Python project structure",
      "Modules",
      "Packages",
      "Imports",
      "Absolute imports",
      "Relative imports",
      "__init__.py",
      "Virtual environments",
      "Dependency management",
      "pyproject.toml",
      "Environment variables",
      "Configuration",
      "Logging",
      "Debugging",
      "pytest",
      "Fixtures",
      "Mocking",
      "Monkeypatching",
      "Type annotations",
      "Optional",
      "Union",
      "Literal",
      "Callable",
      "Generic",
      "TypeVar",
      "Protocol",
      "TypedDict",
      "Dataclasses",
      "Dependency boundaries",
      "Clean project organization",
      "src",
      "tests",
      "configuration",
      "logging",
      "unit tests"
    ],
    "project": "Package the assistant with configuration, logging, and tests",
    "exercises": [
      "Create src, tests, and pyproject.toml from an empty directory.",
      "Write tests using fixtures and mocking."
    ],
    "criteria": "The learner can create a professional Python project from an empty directory. The learner can write unit tests independently. The learner understands Python imports and packaging."
  },
  {
    "id": 3,
    "title": "Async Python and Backend Engineering",
    "short": "Async & APIs",
    "concepts": [
      "async",
      "await",
      "Coroutines",
      "Event loop",
      "Tasks",
      "asyncio.create_task",
      "asyncio.gather",
      "Timeouts",
      "Cancellation",
      "Queues",
      "Locks",
      "Semaphores",
      "Concurrency",
      "Parallelism",
      "Threads",
      "Processes",
      "CPU bound versus IO bound work",
      "Blocking operations",
      "Async HTTP",
      "Async database access",
      "FastAPI internals",
      "Dependency injection",
      "Request lifecycle",
      "Middleware",
      "Exception handlers",
      "Pydantic request validation",
      "Background work",
      "Sequential versus concurrent execution",
      "Blocking calls inside async functions",
      "Task cancellation",
      "Timeout handling",
      "Concurrent HTTP requests"
    ],
    "project": "Build a concurrent FastAPI service",
    "exercises": [
      "Compare sequential and concurrent HTTP requests.",
      "Experiment with cancellation, timeouts, and blocking operations."
    ],
    "criteria": "The learner can explain the Python event loop. The learner knows when async is useful and when it is not. The learner can identify blocking code inside asynchronous systems."
  },
  {
    "id": 4,
    "title": "Pydantic and Pydantic AI",
    "short": "Pydantic & AI",
    "concepts": [
      "BaseModel",
      "Fields",
      "Validation",
      "Field validators",
      "Model validators",
      "Serialization",
      "Deserialization",
      "Nested models",
      "Unions",
      "Discriminated unions",
      "Aliases",
      "Config",
      "Generics",
      "JSON Schema",
      "Settings",
      "Validation errors",
      "Structured domain models",
      "Agent",
      "Model",
      "System instructions",
      "Dependencies",
      "RunContext",
      "Tools",
      "Toolsets",
      "Structured output",
      "Retries",
      "Streaming",
      "Message history",
      "Usage limits",
      "Dependency injection",
      "Multi agent systems",
      "Testing agents",
      "Model abstraction",
      "Agent lifecycle",
      "Agent loop"
    ],
    "project": "Compare a manual agent loop with Pydantic AI",
    "exercises": [
      "Validate nested domain models.",
      "Implement and compare two versions of the same agent."
    ],
    "criteria": "The learner understands what Pydantic AI is doing internally rather than treating it as magic."
  },
  {
    "id": 5,
    "title": "Tools, MCP, Harnesses, and Ontologies",
    "short": "Tools & MCP",
    "concepts": [
      "Tool declaration",
      "Tool name",
      "Description",
      "Input schema",
      "Output schema",
      "Validation",
      "Tool execution",
      "Errors",
      "Permissions",
      "Side effects",
      "Idempotency",
      "MCP Host",
      "MCP Client",
      "MCP Server",
      "Transport",
      "Tools",
      "Resources",
      "Prompts",
      "Schema discovery",
      "Capability discovery",
      "Authorization",
      "Session concepts",
      "search_customer",
      "get_customer_orders",
      "create_support_note",
      "Execution environment",
      "Available tools",
      "Filesystem access",
      "Network access",
      "Context",
      "Memory",
      "Prompt construction",
      "Tool runtime",
      "Observability",
      "Failure handling",
      "Agent loops",
      "Customer",
      "Organization",
      "Order",
      "Invoice",
      "Ticket",
      "Employee",
      "Document"
    ],
    "project": "Build a customer-support MCP server",
    "exercises": [
      "Implement search_customer, get_customer_orders, and create_support_note.",
      "Model relationships between Customer, Order, Invoice, and Ticket."
    ],
    "criteria": "The learner can clearly explain the difference between a tool, MCP, an agent, a harness, a workflow, an ontology, and a model."
  },
  {
    "id": 6,
    "title": "Retrieval Augmented Generation",
    "short": "RAG",
    "concepts": [
      "Document ingestion",
      "Parsing",
      "Cleaning",
      "Chunking",
      "Chunk overlap",
      "Metadata",
      "Embeddings",
      "Vector databases",
      "Cosine similarity",
      "Vector search",
      "Full text search",
      "Postgres",
      "pgvector",
      "Hybrid search",
      "Metadata filtering",
      "Query rewriting",
      "Reranking",
      "Context construction",
      "Prompt construction",
      "Grounding",
      "Citations",
      "Hallucination",
      "Retrieval evaluation",
      "Precision",
      "Recall",
      "Top K",
      "Document",
      "Embedding",
      "Storage",
      "Query",
      "Retrieval",
      "Context",
      "Generation",
      "Citation",
      "Hybrid retrieval",
      "Different chunk sizes",
      "Different Top K values",
      "Reranking enabled and disabled"
    ],
    "project": "Build a retrieval pipeline with citations",
    "exercises": [
      "Compare vector, full-text, and hybrid search.",
      "Vary chunk size, top K, and reranking; test unanswerable questions."
    ],
    "criteria": "The learner can diagnose whether a RAG failure originated in ingestion, retrieval, ranking, context construction, or generation."
  },
  {
    "id": 7,
    "title": "Production AI Engineering",
    "short": "Production",
    "concepts": [
      "Reliable workflows",
      "Retries",
      "Idempotency",
      "Durable execution",
      "DBOS",
      "Workflow recovery",
      "Steps",
      "Queues",
      "Concurrency controls",
      "Scheduling",
      "Background jobs",
      "Observability",
      "Tracing",
      "Structured logging",
      "Metrics",
      "Evaluation",
      "LLM evaluation",
      "Agent evaluation",
      "Test datasets",
      "Regression testing",
      "Prompt evaluation",
      "Tool evaluation",
      "Model comparison",
      "Cost tracking",
      "Token usage",
      "Rate limiting",
      "Fallback models",
      "Secrets",
      "Permissions",
      "Prompt injection",
      "Tool authorization",
      "Human approval",
      "Human in the loop",
      "Failure recovery",
      "Checkpoints",
      "User request",
      "Agent analysis",
      "Data retrieval",
      "RAG",
      "Tool execution",
      "External API",
      "Database update",
      "Workflow interruption",
      "Recovery"
    ],
    "project": "Build a durable AI workflow with recovery",
    "exercises": [
      "Interrupt a workflow and recover without duplicate side effects.",
      "Evaluate model quality, latency, cost, and tool failures."
    ],
    "criteria": "The learner can design an AI system that continues behaving correctly when APIs fail, processes crash, models return bad output, or tools partially succeed."
  }
];
export const resources = [
  [
    "Python documentation",
    "https://docs.python.org/3/",
    "The language, from first principles"
  ],
  [
    "Python standard library",
    "https://docs.python.org/3/library/",
    "The tools already in your toolbox"
  ],
  [
    "pytest",
    "https://docs.pytest.org/",
    "Write tests that build confidence"
  ],
  [
    "FastAPI",
    "https://fastapi.tiangolo.com/",
    "Typed, asynchronous Python APIs"
  ],
  [
    "Pydantic",
    "https://docs.pydantic.dev/",
    "Validation and structured domain models"
  ],
  [
    "Pydantic AI",
    "https://ai.pydantic.dev/",
    "Typed agents and dependency injection"
  ],
  [
    "Model Context Protocol",
    "https://modelcontextprotocol.io/docs/",
    "Connect models, tools, and context"
  ],
  [
    "PostgreSQL",
    "https://www.postgresql.org/docs/",
    "Relational data and reliable persistence"
  ],
  [
    "pgvector",
    "https://github.com/pgvector/pgvector",
    "Vector similarity search for Postgres"
  ],
  [
    "DBOS",
    "https://docs.dbos.dev/",
    "Durable workflows and recovery"
  ],
  [
    "asyncio",
    "https://docs.python.org/3/library/asyncio.html",
    "Concurrency, tasks, and the event loop"
  ],
  [
    "Typing",
    "https://docs.python.org/3/library/typing.html",
    "Build explicit, maintainable contracts"
  ]
];
