// Reference implementations are hidden until explicitly revealed. Checks are run by the learner.
// Tuple: title, prompt, reference implementation, observable checks, first hint, second hint.
const challenge=([title,prompt,solution,checks,hint,another])=>({title,prompt,solution,checks,hints:[hint,another]});
function lab(id,title,docs,memory,exercises,debugging,practical,documentation){return {id,title,docs,memory:challenge(memory),exercises:exercises.map(challenge),debugging:{...challenge(debugging.slice(0,6)),broken:debugging[6]},practical:challenge(practical),documentation}}
const py='https://docs.python.org/3/';
export const labs={
 bindings:lab('bindings','References and isolated state',py+'library/copy.html',
 ['Independent containers','Without a reference example, create two independent event buffers and prove they do not share state.','a = []\nb = []\na.append("login")\nassert b == []','Appending to a must leave b empty.','Draw the two names and their objects.','Allocate each list separately.'],[
 ['Easy · rebinding','Make an alias for a list, rebind the alias, and assert the original is unchanged.','original = [1]\nalias = original\nalias = [2]\nassert original == [1]','The original stays [1]; the alias becomes [2].','Rebinding differs from mutating.','Assign a new list to the alias.'],
 ['Medium · nested isolation','Copy a nested configuration so changing the copied labels does not alter the original.','from copy import deepcopy\na = {"labels": ["safe"]}\nb = deepcopy(a)\nb["labels"].append("new")\nassert a["labels"] == ["safe"]','Assert both outer and inner identities differ.','An outer dict.copy is insufficient.','Use a recursive copy when nested ownership should be independent.'],
 ['Hard · ownership contract','Write add_event(events, event) that returns a new list, leaves its input untouched, and handles an empty input.','def add_event(events, event):\n    return [*events, event]\n\na = []\nb = add_event(a, "login")\nassert a == [] and b == ["login"]','Test empty and nonempty inputs; explain that nested elements remain shared.','Return a new outer container.','Unpacking copies references into a new list.']],
 ['Shared defaults','Fix a collector that leaks events across separate calls.','def record(event, events=None):\n    if events is None:\n        events = []\n    events.append(event)\n    return events','Two calls with omitted events return independent single-item lists.','Defaults are evaluated at definition time.','Use a sentinel and allocate inside the call.','def record(event, events=[]):\n    events.append(event)\n    return events\n\nprint(record("login"))\nprint(record("logout"))'],
 ['Request configuration','Implement per-request overrides without mutating a nested base configuration. Include a test for two consecutive requests.','from copy import deepcopy\ndef configure(base, overrides):\n    result = deepcopy(base)\n    result.update(deepcopy(overrides))\n    return result','Changing one result must not affect base or another result; define whether merging is shallow or recursive.','Write down ownership before implementing.','Copy both base and supplied mutable overrides, then apply the documented merge policy.'],
 'Use the official copy documentation to explain exactly what a shallow copy shares. Record the section and demonstrate a counterexample.'),
 collections:lab('collections','Collection transformations',py+'tutorial/datastructures.html',
 ['Group from memory','Write a function grouping event dictionaries by severity without consulting an implementation.','def group(events):\n    result = {}\n    for event in events:\n        result.setdefault(event["level"], []).append(event)\n    return result','Two error events share a group; info is separate; empty input gives {}.','Each key needs its own bucket.','setdefault can initialize the missing bucket.'],[
 ['Easy · filtering','Return only positive numbers from a list, retaining order.','def positive(values):\n    return [x for x in values if x > 0]','[-1, 0, 2, 1] gives [2, 1].','Create a new collection.','Use a predicate in a comprehension.'],
 ['Medium · counting','Count occurrences of each level in a sequence of event dictionaries.','def count(events):\n    result = {}\n    for event in events:\n        key = event["level"]\n        result[key] = result.get(key, 0) + 1\n    return result','Test repeated, distinct, and empty inputs.','Start unseen levels at zero.','dict.get supplies a default without insertion.'],
 ['Hard · stable deduplication','Deduplicate event IDs while retaining their first occurrence order.','def unique(ids):\n    seen = set()\n    result = []\n    for value in ids:\n        if value not in seen:\n            seen.add(value)\n            result.append(value)\n    return result','[3, 1, 3, 2, 1] gives [3, 1, 2].','Use separate structures for membership and order.','A set tracks seen IDs while a list records first occurrences.']],
 ['Skipped records','Fix the filter so every negative value is removed.','values = [-1, -2, 3]\nvalues = [x for x in values if x >= 0]','The result must be [3], not [-2, 3].','Removing shifts the remaining indexes.','Build the survivor collection instead of editing the traversed one.','values = [-1, -2, 3]\nfor value in values:\n    if value < 0:\n        values.remove(value)\nprint(values)'],
 ['Nested API response','Parse payload["customers"] and return total order amounts by customer ID. Handle customers with no orders.','def totals(payload):\n    return {c["id"]: sum(o["amount"] for o in c.get("orders", []))\n            for c in payload["customers"]}','Test multiple orders, no orders, and an empty customer list; document malformed-input behavior.','Separate shape assumptions from aggregation.','Traverse each customer and aggregate only its own orders.'],
 'Use official dictionary documentation to compare get, setdefault, and direct lookup on missing keys. Include executable examples.'),
 numbers:lab('numbers','Numeric and boolean boundaries',py+'library/decimal.html',
 ['Exact totals','Implement an exact decimal sum from numeric strings.','from decimal import Decimal\ndef total(values):\n    return sum((Decimal(v) for v in values), Decimal("0"))','["0.1", "0.2"] produces Decimal("0.3").','Avoid constructing decimals from floats.','Parse directly from the original string.'],[
 ['Easy · absence','Default a missing timeout to 30 while preserving an explicit zero.','def timeout(value):\n    return 30 if value is None else value','None → 30; 0 → 0; 10 → 10.','Falsy does not mean missing.','Compare with None explicitly.'],
 ['Medium · precision','Calculate 19.99 plus 0.01 with exact decimal arithmetic.','from decimal import Decimal\nresult = Decimal("19.99") + Decimal("0.01")','Result equals Decimal("20.00").','Choose the numeric representation first.','Construct both operands from strings.'],
 ['Hard · rounding policy','Round a decimal amount string to cents using ROUND_HALF_UP.','from decimal import Decimal, ROUND_HALF_UP\ndef cents(value):\n    return Decimal(value).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)','1.005 → 1.01; 1.004 → 1.00.','Rounding is part of the contract.','quantize accepts both a precision and a rounding rule.']],
 ['Truthiness drops valid data','Fix zero being replaced by the default.','supplied = 0\nlimit = 10 if supplied is None else supplied\nassert limit == 0','Zero must remain valid.','or selects a truthy operand.','Distinguish absence with is None.','supplied = 0\nlimit = supplied or 10\nassert limit == 0'],
 ['Invoice arithmetic','Design a function computing quantity × decimal unit price for each line, then rounding the final total to cents.','from decimal import Decimal, ROUND_HALF_UP\ndef invoice(lines):\n    total = sum((Decimal(x["price"]) * x["quantity"] for x in lines), Decimal("0"))\n    return total.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)','Test an empty invoice and fractional-cent products; document total-first rounding.','Keep string prices exact throughout.','Accumulate Decimals and quantize only at the chosen boundary.'],
 'Use Decimal.quantize documentation to demonstrate two rounding modes on the same midpoint amount.'),
 text:lab('text','Files, strings, and JSON',py+'library/json.html',
 ['Parse from memory','Write a function decoding one JSON object and rejecting non-object JSON.','import json\ndef parse(line):\n    value = json.loads(line)\n    if not isinstance(value, dict):\n        raise ValueError("expected object")\n    return value','An object succeeds; [] and null fail.','Parsing syntax and checking shape are separate.','Inspect the decoded Python type.'],[
 ['Easy · strings','Normalize surrounding whitespace and case in a severity string.','def level(text):\n    return text.strip().lower()','" ERROR ": "error"; empty remains empty.','String methods return new values.','Chain strip and lower.'],
 ['Medium · line reader','Read UTF-8 text lines with pathlib and remove trailing newlines.','from pathlib import Path\ndef lines(path):\n    with Path(path).open(encoding="utf-8") as source:\n        return [line.rstrip("\\n") for line in source]','Test non-ASCII text and an empty file.','Own the file in a with block.','Use explicit encoding and strip only newline characters.'],
 ['Hard · JSON lines','Parse nonblank JSON lines; return valid records and numbered error messages separately.','import json\ndef parse_lines(lines):\n    records, errors = [], []\n    for number, line in enumerate(lines, 1):\n        if not line.strip():\n            continue\n        try:\n            records.append(json.loads(line))\n        except json.JSONDecodeError as exc:\n            errors.append((number, str(exc)))\n    return records, errors','A malformed middle line must not hide later valid lines.','Catch only expected parsing failures.','Track line numbers with enumerate starting at one.']],
 ['Invalid shape after parsing','Correct a parser that assumes every valid JSON value is an object.','import json\nvalue = json.loads("[]")\nif not isinstance(value, dict):\n    raise ValueError("expected object")','Reject [] with a clear boundary error instead of an unrelated indexing error.','JSON arrays are valid too.','Validate the decoded shape before field access.','import json\nvalue = json.loads("[]")\nprint(value["level"])'],
 ['Log ingestion adapter','Stream a UTF-8 JSONL file, retain source line numbers, and record malformed records without losing valid ones.','import json\nfrom pathlib import Path\ndef ingest(path):\n    with Path(path).open(encoding="utf-8") as source:\n        for number, line in enumerate(source, 1):\n            if not line.strip():\n                continue\n            try:\n                yield {"line": number, "record": json.loads(line)}\n            except json.JSONDecodeError as exc:\n                yield {"line": number, "error": str(exc)}','Test blank lines, Unicode, invalid syntax, and early consumer termination with explicit resource ownership.','Keep provenance beside the decoded value.','Yield a typed success/error shape for each nonblank line.'],
 'Use JSONDecodeError documentation to report the precise location of invalid input without catching every exception.'),
 functions:lab('functions','Function contracts and closures',py+'tutorial/controlflow.html',
 ['Function factory','From memory, implement a multiplier factory returning a configured callable.','def multiplier(factor):\n    def apply(value):\n        return value * factor\n    return apply','Factories with factors 2 and 3 remain independent.','Return a function, not its result.','The nested callable can read an enclosing binding.'],[
 ['Easy · returns','Write a function returning a normalized string rather than printing it.','def normalize(value):\n    return value.strip().lower()','Callers can compare and store the returned value.','An implicit return is None.','Use an explicit return on the result.'],
 ['Medium · arguments','Write a keyword-only strict option and forward it through a wrapper.','def parse(value, *, strict=False):\n    return int(value) if strict else value\ndef forward(*args, **kwargs):\n    return parse(*args, **kwargs)','forward("2", strict=True) returns 2; positional strict is rejected.','Collection and expansion of arguments use the same symbols in different places.','Forward both *args and **kwargs.'],
 ['Hard · captured state','Implement a counter factory whose returned function increments private state.','def counter():\n    count = 0\n    def next_value():\n        nonlocal count\n        count += 1\n        return count\n    return next_value','One counter returns 1,2; a second starts at 1.','Assignment otherwise creates a local binding.','Declare the enclosing binding nonlocal.']],
 ['Late binding','Fix these callbacks so they return 0, 1, and 2.','callbacks = [lambda i=i: i for i in range(3)]\nassert [f() for f in callbacks] == [0, 1, 2]','Each callable must retain its intended iteration value.','Closures resolve shared bindings when called.','Capture the current value in a default parameter or a factory invocation.','callbacks = [lambda: i for i in range(3)]\nprint([f() for f in callbacks])'],
 ['Configurable pipeline','Write a pipeline function applying a sequence of callables to a value, returning the final result.','def pipeline(value, steps):\n    for step in steps:\n        value = step(value)\n    return value','Test zero steps, two transformations, and an exception in a middle step.','Make each function contract explicit.','Feed each returned value into the next callable.'],
 'Use the official parameter documentation to explain positional-only and keyword-only parameters with one valid and one invalid call.'),
 decorators:lab('decorators','Decorator composition',py+'library/functools.html',
 ['Parameterized decorator','Implement a decorator accepting a prefix, without looking at an implementation first.','from functools import wraps\ndef prefix(text):\n    def decorate(fn):\n        @wraps(fn)\n        def wrapper(*args, **kwargs):\n            return text + fn(*args, **kwargs)\n        return wrapper\n    return decorate','Two differently configured functions retain separate prefixes.','Configuration, decoration, and invocation are separate times.','Return a decorator from the factory and a wrapper from the decorator.'],[
 ['Easy · decorator','Write a decorator that uppercases a string result.','from functools import wraps\ndef uppercase(fn):\n    @wraps(fn)\n    def wrapper(*args, **kwargs):\n        return fn(*args, **kwargs).upper()\n    return wrapper','Arguments and keywords still reach the original function.','Transform the return value.','Call the wrapped function inside the wrapper.'],
 ['Medium · metadata','Preserve name and docstring in a logging wrapper.','from functools import wraps\ndef logged(fn):\n    @wraps(fn)\n    def wrapper(*args, **kwargs):\n        print(fn.__name__)\n        return fn(*args, **kwargs)\n    return wrapper','Compare __name__, __doc__, and __wrapped__ before and after decoration.','Metadata is separate from forwarding.','functools.wraps copies metadata and supplies __wrapped__.'],
 ['Hard · bounded retry','Implement a configurable decorator retrying only TimeoutError, with a positive maximum number of attempts.','from functools import wraps\ndef retry(attempts):\n    if attempts < 1:\n        raise ValueError("positive attempts required")\n    def decorate(fn):\n        @wraps(fn)\n        def wrapper(*args, **kwargs):\n            for attempt in range(attempts):\n                try:\n                    return fn(*args, **kwargs)\n                except TimeoutError:\n                    if attempt == attempts - 1:\n                        raise\n        return wrapper\n    return decorate','Test immediate success, success after one timeout, exhaustion, and an unrelated exception.','Limit both the error class and number of calls.','Re-raise the final retryable failure.']],
 ['Premature execution','Fix the decorator so importing the module does not invoke the decorated function.','def decorate(fn):\n    def wrapper(*args, **kwargs):\n        return fn(*args, **kwargs)\n    return wrapper','The decorated name remains callable; invocation happens only when called.','Check the value returned by the decorator.','Return wrapper, not wrapper().','def decorate(fn):\n    def wrapper():\n        return fn()\n    return wrapper()\n\n@decorate\ndef greeting():\n    return "hello"'],
 ['Retry policy design','Design a retry decorator for a read-only service call with bounded attempts and injected sleep for testing.','# Reference design:\n# Accept attempts, retryable exception types, and sleep_fn.\n# Call once, then delay only before another retry.\n# Re-raise on exhaustion; never retry validation errors.\n# Keep the original signature metadata with wraps.\n# Apply idempotency before using this for side-effecting calls.','Use a fake sleep function; verify no sleep after the last attempt and no retry for ValueError.','Separate delay policy from the operation.','Inject timing and use deterministic failure sequences in tests.'],
 'Use functools.wraps documentation to inspect which attributes are preserved and demonstrate access through __wrapped__.'),
 objects:lab('objects','Objects and resource ownership',py+'library/contextlib.html',
 ['Context manager','Implement a context manager with guaranteed cleanup, without seeing sample code.','class Resource:\n    def __enter__(self):\n        self.closed = False\n        return self\n    def __exit__(self, exc_type, exc, tb):\n        self.closed = True\n        return False','Cleanup occurs on success and failure; exceptions propagate.','There are entry and exit protocol methods.','A false exit result preserves the exception.'],[
 ['Easy · independent instances','Create an EventBuffer whose instances have independent event lists.','class EventBuffer:\n    def __init__(self):\n        self.events = []','Appending to one instance must not affect another.','Place mutable state on the instance.','Allocate in __init__.'],
 ['Medium · dataclass default','Create a Ticket dataclass with an independent labels list.','from dataclasses import dataclass, field\n@dataclass\nclass Ticket:\n    title: str\n    labels: list[str] = field(default_factory=list)','Two tickets must not share labels.','Defaults can be factories.','Use field(default_factory=list).'],
 ['Hard · restoring context','Implement a context manager temporarily changing a dictionary value and restoring it even after an error.','from contextlib import contextmanager\n@contextmanager\ndef override(settings, key, value):\n    sentinel = object()\n    old = settings.get(key, sentinel)\n    settings[key] = value\n    try:\n        yield settings\n    finally:\n        if old is sentinel:\n            settings.pop(key, None)\n        else:\n            settings[key] = old','Test an existing key, a missing key, and an exception inside the block.','A missing value needs a sentinel distinct from None.','Restore in finally.']],
 ['Suppressed failure','Repair a context manager that hides an exception.','class Scope:\n    def __enter__(self): return self\n    def __exit__(self, exc_type, exc, tb):\n        return False','A ValueError raised inside with must reach the caller.','Exit return values control suppression.','Do not return a truthy result unless suppression is intended.','class Scope:\n    def __enter__(self): return self\n    def __exit__(self, exc_type, exc, tb): return True\n\nwith Scope():\n    raise ValueError("lost failure")'],
 ['Typed configuration object','Design a configuration dataclass with independent defaults and a method validating a positive worker count.','from dataclasses import dataclass, field\n@dataclass\nclass Config:\n    workers: int = 4\n    labels: list[str] = field(default_factory=list)\n    def __post_init__(self):\n        if self.workers <= 0:\n            raise ValueError("workers must be positive")','Reject zero workers and verify separate instances own separate lists.','Annotations alone do not enforce invariants.','Validate explicitly during initialization.'],
 'Read the context manager protocol documentation and explain the exception arguments passed to __exit__.'),
 iterators:lab('iterators','Lazy iteration',py+'tutorial/classes.html#generators',
 ['Generator pipeline','Implement a generator yielding only error events from an iterable.','def errors(events):\n    for event in events:\n        if event["level"] == "error":\n            yield event','Only matching events are emitted and input is consumed lazily.','Yield one matching item at a time.','Do not build the entire output list.'],[
 ['Easy · exhaustion','Consume an iterator explicitly until it is exhausted.','items = iter([1, 2])\nassert next(items) == 1\nassert next(items) == 2\nassert next(items, None) is None','Verify the exhausted state remains exhausted.','next accepts an optional fallback.','Call next again after exhaustion.'],
 ['Medium · generator','Yield squared values without materializing them first.','def squares(values):\n    for value in values:\n        yield value * value','A source with side effects should advance only as results are requested.','Computation belongs inside the iteration.','A generator function suspends at yield.'],
 ['Hard · bounded consumption','Implement take(n, iterable) that consumes at most n items.','from itertools import islice\ndef take(n, iterable):\n    if n < 0:\n        raise ValueError("n must be nonnegative")\n    return list(islice(iterable, n))','Test zero, exact length, short input, and an infinite counter.','Avoid fetching item n+1.','Use islice or manually bounded calls to next.']],
 ['Consumed stream','Fix logging that exhausts data before the actual consumer.','values = [x * 2 for x in range(3)]\nprint(values)\nprint(sum(values))','The sum is 6; document the memory tradeoff or recreate a lazy source.','A generator is one-shot.','Materialize once when bounded, or provide a factory for repeatable traversal.','values = (x * 2 for x in range(3))\nprint(list(values))\nprint(sum(values))'],
 ['Streaming analyzer','Design a pipeline from raw lines to decoded events to filtered error events, keeping memory bounded.','import json\ndef decoded(lines):\n    for line in lines:\n        if line.strip():\n            yield json.loads(line)\ndef errors(events):\n    for event in events:\n        if event.get("level") == "error":\n            yield event\n# Consume errors(decoded(source)) inside the file owner scope.','Test partial consumption, malformed JSON, and who closes the source file.','Each stage should consume and produce one item at a time.','Keep resource ownership outside the lazy transformations.'],
 'Use itertools.islice documentation to prove that your bounded consumer does not read one item too many.'),
 imports:lab('imports','Package and import boundaries',py+'tutorial/modules.html',
 ['Module boundary','Write the files and command needed to call a helper in a sibling module within package app.','# app/__init__.py\n# app/parser.py\ndef parse(value):\n    return int(value)\n\n# app/main.py\nfrom .parser import parse\nprint(parse("3"))\n\n# From the package parent: python -m app.main','The module command succeeds from the project root.','Relative imports need package context.','Run with -m from the parent of app.'],[
 ['Easy · explicit import','Import pathlib.Path explicitly and construct a relative path.','from pathlib import Path\npath = Path("data") / "events.jsonl"','The result is a Path, not string concatenation.','Import the name you intend to use.','Use from pathlib import Path.'],
 ['Medium · entry point','Keep importing a module from running its command-line action.','def main():\n    print("running")\nif __name__ == "__main__":\n    main()','Importing is quiet; executing the module calls main.','Entry-point behavior depends on __name__.','Guard side effects under the main condition.'],
 ['Hard · circular dependency','Sketch and implement a third contracts module that removes a circular import between service and adapter.','# contracts.py: define shared Protocols and data types.\n# service.py: import contracts, accept an injected adapter.\n# adapter.py: import contracts, implement its operations.\n# main.py: construct adapter and inject it into service.','Both modules can be imported independently in either order.','Move shared contracts below both consumers.','Compose dependencies only in the entry point.']],
 ['Wrong package context','Repair the command for this otherwise valid relative import.','# From the parent directory, run:\n# python -m app.main\n# Ensure app/__init__.py and app/parser.py exist.','No attempted-relative-import error; do not patch sys.path globally.','Direct file execution lacks normal package context.','Use the module execution form.','# app/main.py\nfrom .parser import parse\n\n# Failing command:\n# python app/main.py'],
 ['Professional package','Design a minimal src-layout analyzer with a public parser, tests, and pyproject.toml.','# pyproject.toml declares build-system and project metadata.\n# src/analyzer/__init__.py\n# src/analyzer/parser.py\n# tests/test_parser.py\n# Install into a clean venv: python -m pip install -e .\n# Run tests using that interpreter: python -m pytest','Verify the import works after editable installation and from a clean environment.','A source tree is not automatically an installed package.','Use project metadata and an environment-specific interpreter.'],
 'Use Python module documentation to explain the difference between __name__ under import and python -m execution.'),
 exceptions:lab('exceptions','Failure contracts',py+'tutorial/errors.html',
 ['Explicit failure','Implement positive_count(text) that rejects nonpositive integers with ValueError.','def positive_count(text):\n    value = int(text)\n    if value <= 0:\n        raise ValueError("count must be positive")\n    return value','Test positive, zero, negative, and nonnumeric input.','Validate after conversion.','Raise a specific exception for the invariant.'],[
 ['Easy · specific catch','Catch only ValueError when converting user input to an integer.','def parse(text):\n    try:\n        return int(text)\n    except ValueError:\n        return None','Invalid numeric text becomes None; unrelated programming failures are not hidden.','Keep the try block narrow.','Catch the documented conversion exception.'],
 ['Medium · cleanup','Demonstrate cleanup running when the operation raises.','events = []\ntry:\n    raise ValueError("bad")\nfinally:\n    events.append("cleanup")','Observe cleanup and propagation of the original error.','Use finally for unconditional cleanup.','Do not return from finally.'],
 ['Hard · cause chain','Translate a parsing error into a domain error while retaining its cause.','class InvalidRecord(Exception): pass\ndef parse(text):\n    try:\n        return int(text)\n    except ValueError as exc:\n        raise InvalidRecord("invalid record") from exc','The domain error has a ValueError __cause__.','Keep both context and a domain-level message.','Use raise ... from exc.']],
 ['Return in finally','Fix a function that reports success despite failure.','def run():\n    try:\n        raise ValueError("failure")\n    finally:\n        print("cleanup")','ValueError must reach the caller.','finally can override prior control flow.','Remove the return from cleanup.','def run():\n    try:\n        raise ValueError("failure")\n    finally:\n        return "success"'],
 ['Failure-aware batch','Process records while collecting expected validation errors, but allow unexpected faults to abort.','def process(values, parse):\n    results, errors = [], []\n    for index, value in enumerate(values):\n        try:\n            results.append(parse(value))\n        except ValueError as exc:\n            errors.append((index, str(exc)))\n    return results, errors','ValueError is recorded; RuntimeError propagates.','Define the recoverable error class.','Catch only at the per-record boundary.'],
 'Use the official exception documentation to demonstrate exception chaining and describe what a traceback preserves.'),
 typing:lab('typing','Typed dependency contracts',py+'library/typing.html',
 ['Protocol from memory','Define a Writer Protocol and a function that accepts any compatible implementation.','from typing import Protocol\nclass Writer(Protocol):\n    def write(self, text: str) -> None: ...\ndef report(writer: Writer, text: str) -> None:\n    writer.write(text)','A compatible class need not inherit Writer; an incompatible signature should fail static checking.','Describe supported operations rather than concrete classes.','Protocol provides structural subtyping.'],[
 ['Easy · optional value','Annotate a function that turns a string or None into a string.','def normalize(value: str | None) -> str:\n    return "" if value is None else value.strip()','Both branches return str.','Narrow the None case first.','An explicit branch narrows the remaining value.'],
 ['Medium · typed dictionary','Define an event TypedDict with a required ID and optional label.','from typing import TypedDict, NotRequired\nclass Event(TypedDict):\n    id: int\n    label: NotRequired[str]','Check a missing required ID statically; demonstrate ordinary dict runtime behavior.','Optional presence differs from a None value.','Use NotRequired for a key that can be absent.'],
 ['Hard · generic result','Type a first-item helper preserving its input element type.','from typing import TypeVar\nT = TypeVar("T")\ndef first(values: list[T]) -> T:\n    if not values:\n        raise ValueError("empty")\n    return values[0]','A list[str] yields str and list[int] yields int in the checker; empty input fails explicitly.','Link the parameter and result types.','Use the same type variable in both locations.']],
 ['Annotations are not conversion','Fix a typed boundary that adds a string to an integer.','def parse_count(raw: str) -> int:\n    return int(raw)\nprint(parse_count("3") + 1)','Valid numeric text produces 4; invalid text raises a documented error.','Annotations do not coerce values.','Convert or validate at the boundary.','def parse_count(raw: str) -> int:\n    return raw\nprint(parse_count("3") + 1)'],
 ['Typed configuration boundary','Define a typed configuration from environment strings; validate workers and preserve an explicit zero timeout.','from dataclasses import dataclass\n@dataclass\nclass Config:\n    workers: int\n    timeout: float\ndef load(env):\n    workers = int(env.get("WORKERS", "4"))\n    timeout = float(env.get("TIMEOUT", "30"))\n    if workers <= 0 or timeout < 0:\n        raise ValueError("invalid config")\n    return Config(workers, timeout)','Test missing values, zero timeout, nonnumeric workers, and negative timeout.','Static shape and runtime validation solve different problems.','Parse all strings before constructing the typed value.'],
 'Use official Protocol documentation to contrast structural typing with inheritance and explain whether runtime_checkable checks full signatures.'),
 testing:lab('testing','Behavioral tests', 'https://docs.pytest.org/en/stable/',
 ['Test from memory','Write a pytest test asserting that malformed numeric input raises ValueError.','import pytest\ndef test_bad_input():\n    with pytest.raises(ValueError):\n        int("invalid")','The test fails if no error or a different error is raised.','Assert the specific failure contract.','pytest.raises is a context manager.'],[
 ['Easy · assertion','Write a behavior test for a normalizer trimming and lowercasing text.','def normalize(text): return text.strip().lower()\ndef test_normalize():\n    assert normalize(" ERROR ") == "error"','Change the implementation to verify the test detects a regression.','Assert the visible return value.','Supply an input requiring both transformations.'],
 ['Medium · matrix','Parameterize empty, mixed-case, and padded inputs.','import pytest\n@pytest.mark.parametrize("raw,expected", [("", ""), ("Hi", "hi"), (" A ", "a")])\ndef test_normalize(raw, expected):\n    assert raw.strip().lower() == expected','All cases collect and have independent results.','Avoid duplicating the test body.','Use mark.parametrize with named arguments.'],
 ['Hard · fake dependency','Test a report service with a fake writer that records output.','class FakeWriter:\n    def __init__(self): self.messages = []\n    def write(self, text): self.messages.append(text)\ndef report(writer, total): writer.write(str(total))\ndef test_report():\n    writer = FakeWriter()\n    report(writer, 3)\n    assert writer.messages == ["3"]','No real I/O; verify only the observable dependency contract.','Inject the collaborator.','Record interactions in a tiny in-memory implementation.']],
 ['Fixture state leak','Fix a mutable fixture leaking data between tests.','import pytest\n@pytest.fixture\ndef events():\n    return []','Each test starts with an empty list regardless of order.','Fixture scope controls reuse.','Use function scope or explicitly isolate mutable state.','import pytest\n@pytest.fixture(scope="session")\ndef events(): return []\ndef test_one(events): events.append("event")\ndef test_two(events): assert events == []'],
 ['Adapter contract suite','Design tests shared by a fake repository and a file-backed repository: create, lookup, missing key, and duplicate ID.','# Parameterize a repository factory fixture.\n# Run the same contract assertions against each implementation.\n# Use tmp_path for file storage.\n# Keep the duplicate-ID behavior explicit and identical.','Both implementations must pass the same observable contract.','Test an interface promise rather than internal method calls.','A factory fixture can construct fresh implementations per test.'],
 'Use official pytest fixture documentation to demonstrate cleanup after a failing test.'),
 async:lab('async','Async coordination',py+'library/asyncio-task.html',
 ['Three concurrent tasks','Create three concurrent tasks and collect their results from memory.','import asyncio\nasync def work(n):\n    await asyncio.sleep(0.01)\n    return n * 2\nasync def main():\n    tasks = [asyncio.create_task(work(n)) for n in range(3)]\n    return await asyncio.gather(*tasks)\nprint(asyncio.run(main()))','Results are [0, 2, 4]; the three waits overlap.','Scheduling and awaiting are distinct.','Create task handles, then await their combined result.'],[
 ['Easy · await','Invoke an async function and obtain its actual return value.','import asyncio\nasync def answer(): return 42\nasync def main(): return await answer()\nassert asyncio.run(main()) == 42','No never-awaited coroutine warning.','Calling async def returns a coroutine.','Drive it with await inside the running loop.'],
 ['Medium · bounded work','Limit simultaneous work to two tasks with a semaphore.','import asyncio\nasync def run(values, worker):\n    sem = asyncio.Semaphore(2)\n    async def limited(value):\n        async with sem:\n            return await worker(value)\n    return await asyncio.gather(*(limited(v) for v in values))','Instrument active count; its maximum must never exceed two.','The limiter must be shared.','Construct one semaphore outside all workers.'],
 ['Hard · timeout and cleanup','Bound an operation with a timeout and prove cleanup still runs.','import asyncio\nasync def operation(events):\n    try:\n        await asyncio.sleep(10)\n    finally:\n        events.append("cleaned")\nasync def main():\n    events = []\n    try:\n        async with asyncio.timeout(0.01):\n            await operation(events)\n    except TimeoutError:\n        assert events == ["cleaned"]\nasyncio.run(main())','Timeout reaches the owner; cleanup occurs; cancellation is not swallowed.','Timeouts interact with cancellation.','Place resource cleanup in finally.']],
 ['Blocking the event loop','Repair the coroutine that stalls unrelated tasks.','import asyncio\nasync def fetch():\n    await asyncio.sleep(1)\n    return "done"\n# For truly blocking I/O: await asyncio.to_thread(blocking_call)','Run a heartbeat concurrently and show it remains responsive.','async def does not transform synchronous work.','Use a nonblocking API or offload appropriate blocking I/O.','import time\nasync def fetch():\n    time.sleep(1)\n    return "done"'],
 ['Async worker queue','Design a bounded async queue with two consumers, completion accounting, and orderly shutdown.','import asyncio\nasync def run(items, process):\n    queue = asyncio.Queue(maxsize=4)\n    async def worker():\n        while True:\n            item = await queue.get()\n            try:\n                if item is None: return\n                await process(item)\n            finally:\n                queue.task_done()\n    async with asyncio.TaskGroup() as group:\n        for _ in range(2): group.create_task(worker())\n        for item in items: await queue.put(item)\n        for _ in range(2): await queue.put(None)\n        await queue.join()','Use a documented None sentinel; test empty input, worker failure, and backpressure.','Decide who owns workers and failures.','TaskGroup owns worker lifetimes; task_done belongs in finally.'],
 'Use asyncio.gather and TaskGroup documentation to explain their different sibling-failure behavior, then reproduce one case.'),
 pydantic:lab('pydantic','Validated API boundaries','https://docs.pydantic.dev/latest/concepts/models/',
 ['Model a payload','Model a support-note payload with a positive customer ID and nonempty text without viewing code first.','from pydantic import BaseModel, Field\nclass Note(BaseModel):\n    customer_id: int = Field(gt=0)\n    text: str = Field(min_length=1)','Valid payload succeeds; zero ID and empty text produce validation errors.','Declare the shape and constraints together.','Use BaseModel and Field constraints.'],[
 ['Easy · required field','Define a model with one required string title.','from pydantic import BaseModel\nclass Ticket(BaseModel):\n    title: str','A missing title fails validation.','A required field has no default.','Annotate the field on BaseModel.'],
 ['Medium · nested model','Validate a customer with a list of orders containing integer IDs.','from pydantic import BaseModel\nclass Order(BaseModel): id: int\nclass Customer(BaseModel):\n    id: int\n    orders: list[Order]','An invalid nested order ID reports its location in the list.','Use a model for each domain shape.','Annotate the collection with the nested model type.'],
 ['Hard · cross-field invariant','Reject a range whose end is before its start.','from pydantic import BaseModel, model_validator\nclass Range(BaseModel):\n    start: int\n    end: int\n    @model_validator(mode="after")\n    def ordered(self):\n        if self.end < self.start:\n            raise ValueError("end before start")\n        return self','Test equal, increasing, and decreasing endpoints.','Neither field alone establishes the invariant.','An after model validator sees parsed fields together.']],
 ['Bypassed validation','Repair untrusted data entering a model without validation.','from pydantic import BaseModel, Field\nclass Count(BaseModel): value: int = Field(gt=0)\nCount.model_validate({"value": -1})','The invalid payload must raise ValidationError.','Some constructors deliberately skip validation.','Use model_validate at external boundaries.','from pydantic import BaseModel, Field\nclass Count(BaseModel): value: int = Field(gt=0)\nitem = Count.model_construct(value=-1)\nprint(item.value)'],
 ['External API model','Design nested Pydantic models for an external customer API, validating order amounts and serializing a clean response.','from pydantic import BaseModel, Field\nfrom decimal import Decimal\nclass Order(BaseModel):\n    id: int = Field(gt=0)\n    amount: Decimal = Field(ge=0)\nclass Customer(BaseModel):\n    id: int = Field(gt=0)\n    orders: list[Order] = Field(default_factory=list)\n# Validate with Customer.model_validate(payload).\n# Serialize with model_dump(mode="json").','Test missing orders, invalid amount, independent defaults, and JSON serialization.','Separate nested shape validation from business behavior.','Give collections factories and constrain the fields that cross the boundary.'],
 'Use Pydantic serialization documentation to compare model_dump in Python and JSON modes for a Decimal field.'),
 database:lab('database','Database access and transactions','https://docs.python.org/3/library/sqlite3.html',
 ['Parameterized lookup','Write a parameterized customer lookup using Python sqlite3.','def lookup(connection, customer_id):\n    return connection.execute("SELECT name FROM customers WHERE id = ?", (customer_id,)).fetchone()','The input is bound as data, and a missing row returns None.','Separate SQL syntax from values.','Supply parameters as a sequence.'],[
 ['Easy · missing row','Handle a lookup returning no database row.','def name(connection, customer_id):\n    row = connection.execute("SELECT name FROM customers WHERE id = ?", (customer_id,)).fetchone()\n    return None if row is None else row[0]','No indexing error on a missing customer.','A successful query can have zero rows.','Check for None before indexing.'],
 ['Medium · transaction','Insert two related records atomically using a sqlite3 connection context.','def create_pair(connection, first, second):\n    with connection:\n        connection.execute("INSERT INTO items(id) VALUES (?)", (first,))\n        connection.execute("INSERT INTO items(id) VALUES (?)", (second,))','A unique-constraint failure on the second insert must roll back the first.','The transaction spans both operations.','Use one transaction boundary and let failures propagate.'],
 ['Hard · deduplicated write','Use a unique request key to prevent duplicate SQLite note creation.','def create_once(connection, key, text):\n    with connection:\n        connection.execute("INSERT INTO notes(request_key, text) VALUES (?, ?) ON CONFLICT(request_key) DO NOTHING", (key, text))\n    return connection.execute("SELECT text FROM notes WHERE request_key = ?", (key,)).fetchone()[0]\n# Schema requires UNIQUE(request_key).','Two submissions with the same key create one row; define conflicting-payload policy.','An application-level exists check races.','Enforce uniqueness in storage.']],
 ['Unsafe query construction','Fix SQL built by concatenating an external identifier.','def lookup(connection, customer_id):\n    return connection.execute("SELECT name FROM customers WHERE id = ?", (customer_id,)).fetchall()','A value containing SQL syntax must remain an ordinary bound value.','Values must not become SQL syntax.','Use driver parameter binding.','def lookup(connection, customer_id):\n    sql = "SELECT name FROM customers WHERE id = " + customer_id\n    return connection.execute(sql).fetchall()'],
 ['Repository boundary','Design a repository returning a typed customer or None, with parameterized access and explicit connection ownership.','from dataclasses import dataclass\n@dataclass\nclass Customer:\n    id: int\n    name: str\ndef get_customer(connection, customer_id):\n    row = connection.execute("SELECT id, name FROM customers WHERE id = ?", (customer_id,)).fetchone()\n    return Customer(*row) if row else None','Test found/missing cases, malformed input, and connection cleanup at the owner scope.','Keep driver rows out of domain callers.','Translate rows to domain values at the adapter boundary.'],
 'Use sqlite3 documentation to determine what its connection context manager commits, rolls back, and does not close.'),
 agents:lab('agents','Model and tool orchestration','https://ai.pydantic.dev/agents/',
 ['Manual loop','Sketch a bounded model-tool loop from memory, including tool-result history.','def run(model, tools, messages, limit=4):\n    for _ in range(limit):\n        response = model(messages)\n        messages.append(response)\n        if response["kind"] == "final":\n            return response["text"]\n        name = response["tool"]\n        if name not in tools: raise ValueError("unknown tool")\n        result = tools[name](**response["arguments"])\n        messages.append({"kind": "tool_result", "result": result})\n    raise RuntimeError("budget exceeded")\n# Simplified fake-model message format, not a provider wire protocol.','Test one tool then final, unknown tool, and nontermination.','Each step needs a recorded outcome.','Append the tool result and bound the number of iterations.'],[
 ['Easy · dispatch','Dispatch a tool name through an explicit allowlist.','def dispatch(name, args, tools):\n    if name not in tools: raise ValueError("unknown tool")\n    return tools[name](**args)','Unknown names never execute code.','Do not eval model text.','Look up an allowed callable by name.'],
 ['Medium · history','Append a model tool request and its result to a message list in order.','def record(messages, call, result):\n    return [*messages, call, {"kind": "tool_result", "call_id": call["id"], "result": result}]','The result links to the same call ID and follows the request.','The next model step needs both request and outcome.','Keep a stable call identifier.'],
 ['Hard · budget','Implement a loop that accepts a final answer or stops after three nonfinal responses.','def run(model, messages):\n    for _ in range(3):\n        response = model(messages)\n        messages.append(response)\n        if response["kind"] == "final": return response\n    raise RuntimeError("request budget exceeded")','An always-nonfinal fake model is called exactly three times.','Termination must not depend solely on model cooperation.','Place an explicit bound around the loop.']],
 ['Forgotten tool outcome','Repair a loop that repeatedly asks the model for the same information.','response = model(messages)\nmessages.append(response)\nresult = tools[response["tool"]](**response["arguments"])\nmessages.append({"kind": "tool_result", "call_id": response["id"], "result": result})','A fake model should see the result on its next invocation.','Inspect the history, not only the tool execution.','Persist the result in the message format expected by the model adapter.','response = model(messages)\nresult = tools[response["tool"]](**response["arguments"])\nresponse = model(messages)'],
 ['Support assistant loop','Design a fake-model agent loop with authorized read tools, typed final output, and bounded failure handling.','# Define a provider adapter returning final or tool-call variants.\n# Validate arguments and derive caller identity from run context.\n# Dispatch only allowed tools; record call IDs and outcomes.\n# Bound attempts and validate the final result.\n# Test unknown tools, denied access, invalid output, and endless calls.','Use deterministic fake responses and assert complete trajectories, not only final text.','Separate model protocol, business tools, and orchestration.','Make every boundary testable without a live model.'],
 'Use Pydantic AI documentation to identify the library equivalents of your manual loop, dependencies, output contract, and usage limits.'),
 tools:lab('tools','Tool contracts and permissions','https://modelcontextprotocol.io/specification/latest/server/tools',
 ['Tool declaration','Declare a customer lookup tool with a name, description, and input JSON Schema from memory.','tool = {"name": "get_customer", "description": "Read one customer by ID", "inputSchema": {"type": "object", "properties": {"customer_id": {"type": "integer", "minimum": 1}}, "required": ["customer_id"], "additionalProperties": False}}','The required field, type, and minimum are explicit.','Describe one narrow operation.','Input schema is an object with properties and required fields.'],[
 ['Easy · allowed names','Reject a tool name absent from a registry.','def resolve(name, registry):\n    if name not in registry: raise ValueError("unknown tool")\n    return registry[name]','Unknown names fail before any side effect.','Registry membership is explicit.','No dynamic code evaluation is needed.'],
 ['Medium · tenant check','Authorize a customer operation against a trusted caller tenant.','def authorize(caller, customer):\n    if caller["tenant_id"] != customer["tenant_id"]:\n        raise PermissionError("cross-tenant access")','A mismatched tenant is denied even for an otherwise valid customer ID.','Validation is not authorization.','Compare stored resource ownership with trusted caller context.'],
 ['Hard · stable errors','Return stable error codes for invalid input, denied access, and missing customers.','def result_error(code, message):\n    return {"ok": False, "error": {"code": code, "message": message}}\n# Map only known errors at the boundary; log unexpected faults separately.','Tests distinguish the three error conditions without parsing prose.','Use a structural error contract.','Keep machine-readable codes separate from display messages.']],
 ['Untrusted identity','Fix authorization that trusts identity supplied by a model.','def create_note(args, trusted_context, repository):\n    customer = repository.get_customer(args["customer_id"])\n    if customer.tenant_id != trusted_context.tenant_id:\n        raise PermissionError("denied")\n    return repository.add_note(customer.id, args["text"])','Changing args tenant_id must not change caller authority.','The model controls arguments.','Derive identity from authenticated run context.','def create_note(args, repository):\n    if args["tenant_id"] == repository.owner(args["customer_id"]):\n        return repository.add_note(args["customer_id"], args["text"])'],
 ['Write-tool design','Design create_support_note with schema validation, authorization, idempotency, and a structured result.','# Validate customer_id, nonempty text, and request_key.\n# Resolve trusted caller and enforce tenant/write permission.\n# Persist request identity and note atomically.\n# Return the original result on equivalent retries.\n# Reject same-key/different-payload conflicts.','Test denied callers, malformed input, duplicate submissions, and uncertain write outcomes.','The contract includes more than the input schema.','Place permission and idempotency checks at execution/storage boundaries.'],
 'Read the MCP tool specification and distinguish protocol errors from tool-execution errors with an example of each.'),
 rag:lab('rag','Retrieval and evidence','https://github.com/pgvector/pgvector',
 ['Retrieval function','Implement cosine similarity for two nonzero, equal-length vectors without viewing code.','from math import sqrt\ndef cosine(a, b):\n    if len(a) != len(b): raise ValueError("dimensions differ")\n    denom = sqrt(sum(x*x for x in a) * sum(y*y for y in b))\n    if denom == 0: raise ValueError("zero vector")\n    return sum(x*y for x,y in zip(a,b)) / denom','Parallel → 1; perpendicular → 0; opposite → -1; zero vectors rejected.','Compute a dot product divided by both norms.','Validate dimensions and denominator before division.'],[
 ['Easy · top K','Return the three highest-scored items without modifying the input.','def top_k(items, k=3):\n    if k < 0: raise ValueError("negative k")\n    return sorted(items, key=lambda x: x["score"], reverse=True)[:k]','Test fewer than three items, ties, and unchanged input.','Use an explicit score key.','Sorted returns a new list.'],
 ['Medium · filter first','Select the highest-scoring authorized documents for one tenant.','def retrieve(documents, tenant_id, k):\n    allowed = [d for d in documents if d["tenant_id"] == tenant_id]\n    return sorted(allowed, key=lambda d: d["score"], reverse=True)[:k]','No returned document belongs to another tenant.','Authorization is a retrieval boundary.','Filter before constructing the result context.'],
 ['Hard · rank fusion','Combine two ranked ID lists with reciprocal rank fusion using a positive constant.','def fuse(rankings, constant=60):\n    scores = {}\n    for ranking in rankings:\n        for rank, doc_id in enumerate(dict.fromkeys(ranking), 1):\n            scores[doc_id] = scores.get(doc_id, 0) + 1 / (constant + rank)\n    return sorted(scores, key=scores.get, reverse=True)','A document high in both lists should score strongly; duplicates within one list count once.','Raw scores may be incomparable.','Accumulate reciprocal rank contributions.']],
 ['Reversed distance ranking','Fix retrieval returning the least similar vectors first.','def nearest(items, k):\n    return sorted(items, key=lambda x: x["distance"])[:k]','Distance zero ranks ahead of distance one.','Distance and similarity have opposite ordering.','Lower distance is better.','def nearest(items, k):\n    return sorted(items, key=lambda x: x["distance"], reverse=True)[:k]'],
 ['Grounded retrieval function','Design a retrieval adapter with tenant filtering, candidate retrieval, optional reranking, bounded context, and source IDs.','# Filter by trusted tenant and active document version.\n# Retrieve broad lexical/vector candidates; deduplicate source IDs.\n# Optionally rerank existing candidates.\n# Select context within budget; preserve evidence identifiers.\n# Return no-evidence explicitly when support is absent.','Compare against labeled queries, including no-answer and cross-tenant cases.','Separate retrieval from answer generation.','Evaluate candidate recall before blaming the reranker or prompt.'],
 'Use pgvector documentation to identify the cosine-distance operator and the ordering required for nearest-neighbor queries.'),
 workflow:lab('workflow','Durable work and idempotency','https://docs.dbos.dev/python/tutorials/workflow-tutorial',
 ['State before effects','From memory, describe a write operation that safely recognizes a repeated request.','# Persist a unique request key together with the effect/result.\n# Return the recorded result on an equivalent retry.\n# Reject a conflicting payload under the same key.\n# Use a database transaction/unique constraint, not only an in-memory check.','Two concurrent retries must create one logical effect.','Request identity needs durable ownership.','The check and write must be atomic.'],[
 ['Easy · classify failures','Write a retry predicate accepting TimeoutError but rejecting ValueError.','def retryable(error):\n    return isinstance(error, TimeoutError)','TimeoutError → True; ValueError → False.','Not every failure is transient.','Use an explicit permitted error class.'],
 ['Medium · attempt budget','Call an operation at most three times on TimeoutError and propagate exhaustion.','def run(operation):\n    for attempt in range(3):\n        try: return operation()\n        except TimeoutError:\n            if attempt == 2: raise','Test immediate success and exactly three failed calls.','Keep a finite loop.','Re-raise on the final permitted attempt.'],
 ['Hard · approval binding','Validate that an approval matches both the action digest and the authorized reviewer.','def approved(record, digest, reviewer_id):\n    return record["digest"] == digest and record["reviewer_id"] == reviewer_id and record["decision"] == "approve"','A changed action, wrong reviewer, or rejection must fail; add expiry to a real implementation.','Approval concerns a specific action.','Bind the decision to immutable action data and identity.']],
 ['Duplicate uncertain write','Fix a retry that changes the idempotency key for the same logical request.','def submit(client, request_key, payload):\n    for attempt in range(3):\n        try: return client.write(payload, idempotency_key=request_key)\n        except TimeoutError:\n            if attempt == 2: raise','Every retry sends the same key; conflicting payload reuse is rejected by storage.','A lost response does not prove a failed write.','Create the logical request key outside the retry loop.','from uuid import uuid4\ndef submit(client, payload):\n    for _ in range(3):\n        try: return client.write(payload, idempotency_key=str(uuid4()))\n        except TimeoutError: pass'],
 ['Recoverable support workflow','Design a workflow that reads data, proposes a support note, pauses for approval, writes idempotently, and resumes after a crash.','# Durable states: received → analyzed → awaiting_approval → approved → applied.\n# Persist proposal and action digest before asking for approval.\n# Recheck authorization at execution time.\n# Isolate the external write with a stable idempotency key.\n# Record result and reconcile uncertain outcomes during recovery.','Crash-test before approval, after approval, and after the external write but before result recording.','List durable state and external side effects separately.','Recovery must not reinterpret an old approval for a changed proposal.'],
 'Use the DBOS workflow and step documentation to identify which operations belong in steps and how their results affect recovery.')
};

labs.mcp={...labs.tools,id:'mcp',title:'MCP server boundaries',docs:'https://py.sdk.modelcontextprotocol.io/',
 memory:challenge(['Declare an MCP tool','Using the current MCP Python SDK, declare a typed read-only tool returning a customer display name.','# MCP Python SDK 2.x\nfrom mcp.server import MCPServer\nserver = MCPServer("Customer lab")\n@server.tool()\ndef get_customer_name(customer_id: int) -> str:\n    """Read a customer display name by positive ID."""\n    if customer_id <= 0: raise ValueError("positive ID required")\n    return {1: "Sample customer"}.get(customer_id, "Not found")\n# Run with: mcp dev server.py','Discover the tool in an MCP client and inspect the generated input schema.','Use the SDK server and its tool decorator.','Annotate parameters and return type; retain runtime domain validation.']),
 practical:challenge(['Create an MCP customer tool','Design and implement a discoverable customer lookup tool, including invalid-input and missing-customer behavior.','# Use MCPServer from mcp.server (SDK 2.x).\n# Register a typed function with @server.tool().\n# Inject or close over a read-only repository.\n# Validate the identifier, enforce caller permissions at the boundary,\n# and return a documented structured result.\n# Inspect discovery and invoke valid, missing, and invalid inputs.','Test actual discovery and tool invocation; do not assume registering an ordinary function exposes it.','Keep the protocol adapter separate from business lookup.','Verify tools/list and tools/call using a client or the SDK development inspector.']),
 debugging:{...challenge(['Undiscoverable MCP operation','Fix a Python lookup function that is never registered with the MCP server.','# MCP Python SDK 2.x\nfrom mcp.server import MCPServer\nserver = MCPServer("Customer lab")\n@server.tool()\ndef lookup(customer_id: int) -> str:\n    """Look up the display name of a customer."""\n    return str(customer_id)','The lookup must appear in tool discovery with a typed input.','Python function definition alone does not register protocol capabilities.','Apply the server tool registration decorator.']),broken:'from mcp.server import MCPServer\nserver = MCPServer("Customer lab")\ndef lookup(customer_id: int) -> str:\n    return str(customer_id)\n# Client tool discovery does not show lookup.'},
 documentation:'Use the current official MCP Python SDK documentation to expose a tool and distinguish its discovery schema from a resource.'};
labs.fastapi={...labs.pydantic,id:'fastapi',title:'Async HTTP boundaries',docs:'https://fastapi.tiangolo.com/tutorial/dependencies/',
 memory:challenge(['Injected HTTP handler','Implement a FastAPI handler receiving a repository through a dependency.','from fastapi import FastAPI, Depends\napp = FastAPI()\ndef repository():\n    return {1: {"id": 1}}\n@app.get("/customers/{customer_id}")\ndef customer(customer_id: int, repo=Depends(repository)):\n    return repo.get(customer_id)','A test can override repository without changing the route implementation.','Declare the provider at the handler boundary.','Use Depends rather than constructing the repository inside the handler.']),
 debugging:{...challenge(['Unused dependency override','Fix a route that constructs its own repository and bypasses injected test data.','from fastapi import Depends\n@app.get("/customers/{customer_id}")\ndef customer(customer_id: int, repo=Depends(repository)):\n    return repo.get(customer_id)','Overriding repository must change the handler data source.','Look at where the handler obtains its dependency.','Move construction into an injected provider.']),broken:'@app.get("/customers/{customer_id}")\ndef customer(customer_id: int):\n    repo = RealRepository()\n    return repo.get(customer_id)\n# Test overrides repository(), but the real storage is still used.'},
 practical:challenge(['Validated report endpoint','Design a FastAPI report endpoint with a validated positive limit, injected storage, and explicit not-found handling.','from fastapi import FastAPI, Depends, Query, HTTPException\napp = FastAPI()\ndef repository(): return {}\n@app.get("/reports/{report_id}")\ndef report(report_id: int, limit: int = Query(10, gt=0), repo=Depends(repository)):\n    value = repo.get(report_id)\n    if value is None: raise HTTPException(404, "Report not found")\n    return value[:limit]','Test valid requests, zero limit, missing report, and a fake repository override.','Keep validation, lookup, and HTTP translation at separate boundaries.','Use Query constraints, Depends, and a deliberate HTTPException.']),
 documentation:'Use FastAPI dependency documentation to override a provider in a test and explain the resource lifetime you chose.'};
labs.concurrency={...labs.async,id:'concurrency',title:'Concurrent state and ownership',
 debugging:{...challenge(['Lost concurrent update','Fix two tasks overwriting a shared counter after a suspension point.','import asyncio\nasync def main():\n    count = 0\n    lock = asyncio.Lock()\n    async def increment():\n        nonlocal count\n        async with lock:\n            old = count\n            await asyncio.sleep(0)\n            count = old + 1\n    await asyncio.gather(increment(), increment())\n    assert count == 2\nasyncio.run(main())','Two increments must yield two even with an await between read and write.','Both tasks can read the old value before either writes.','Own one shared lock covering the complete read-modify-write region.']),broken:'import asyncio\nasync def main():\n    count = 0\n    async def increment():\n        nonlocal count\n        old = count\n        await asyncio.sleep(0)\n        count = old + 1\n    await asyncio.gather(increment(), increment())\n    assert count == 2\nasyncio.run(main())'}};
labs.security={...labs.tools,id:'security',title:'Trust and access boundaries',
 debugging:{...challenge(['Credential in a trace','Repair logging that exposes a credential from a request context.','def safe_event(context):\n    return {"request_id": context["request_id"], "operation": context["operation"]}\n# Log only explicitly approved fields.','The output contains no token even if new sensitive fields are added to context.','A denylist can miss future secret fields.','Build an allowlisted log shape.']),broken:'def trace(context):\n    print(context)\ntrace({"request_id": "demo", "operation": "read", "token": "example-placeholder"})'},
 documentation:'Use official MCP authorization documentation to explain why a valid tool schema does not establish caller permission.'};

// A focused lab supplies executable practice alongside the exact milestone's explanation and official reading.
export function labFor(m){
 const id=m.id;
 if(['bindings','mutability','identity','shallow-copy','deep-copy','mutable-defaults'].includes(id))return labs.bindings;
 if(['truth','numbers'].includes(id))return labs.numbers;
 if(['strings','files','json'].includes(id))return labs.text;
 if(['lists','dicts','sets','unpack','loops','comprehensions'].includes(id))return labs.collections;
 if(['exceptions','exception-tests','debugging'].includes(id))return labs.exceptions;
 if(id.includes('decorator'))return labs.decorators;
 if(['iterables','iterators','generators','generator-pipelines','generator-cleanup'].includes(id))return labs.iterators;
 if(m.week===1)return labs.functions;
 if(m.week===2)return labs.objects;
 if(['packages','environment','configuration'].includes(id))return labs.imports;
 if(m.tags.includes('typing'))return labs.typing;
 if(m.week===3)return labs.testing;
 if(id.startsWith('fastapi'))return labs.fastapi;
 if(['locks','semaphores','queues'].includes(id))return labs.concurrency;
 if(m.week===4)return labs.async;
 if(m.week===5&&m.order<=8)return labs.pydantic;
 if(m.week===5)return labs.agents;
 if(id.startsWith('ontology')||id==='idempotency')return labs.database;
 if(id.startsWith('mcp'))return labs.mcp;
 if(['secrets','prompt-injection','tool-permissions'].includes(id))return labs.security;
 if(m.week===6)return labs.tools;
 if(m.week===7)return labs.rag;
 return labs.workflow;
}
